In [1]:
import pandas as pd
import mteb

In [32]:
benchmark_scores_df = pd.read_csv("../../data/datasets/mteb_22_08_2026.csv")
benchmark_scores_df.head(30)

,Rank,Model,Model Type,Open Weights,Instruction Tuned,ST Compatible,Modalities,License,Release Date,Memory (MB),...,Mean (TaskType),BitextMining,Classification,Clustering,InstructionReranking,MultilabelClassification,PairClassification,Reranking,Retrieval,STS
0,1,microsoft/harrier-oss-v1-27b,dense,True,True,True,text,mit,2026-03-27,51515.0,...,64.20,86.02,79.95,58.93,5.39,36.44,85.44,67.35,78.27,79.99
1,2,tencent/KaLM-Embedding-Gemma3-12B-2511,dense,True,True,True,text,NaN,2025-11-06,44884.0,...,62.51,83.76,77.88,55.77,5.49,33.03,84.73,67.27,75.66,79.02
2,3,nvidia/llama-embed-nemotron-8b,dense,True,True,True,text,https://huggingface.co/nvidia/llama-embed-nemo...,2025-10-23,28629.0,...,61.09,81.72,73.21,54.35,10.82,29.86,83.97,67.78,68.69,79.41
3,4,Qwen/Qwen3-Embedding-8B,dense,True,True,True,text,apache-2.0,2025-06-05,14433.0,...,61.69,80.89,74.00,57.65,10.06,28.66,86.40,65.63,70.88,81.08
4,5,google/gemini-embedding-001,dense,False,True,False,text,NaN,2025-07-14,NaN,...,59.59,79.28,71.82,54.59,5.18,29.16,83.63,65.58,67.71,79.40
5,6,Qwen/Qwen3-Embedding-4B,dense,True,True,True,text,apache-2.0,2025-06-05,7671.0,...,60.86,79.36,72.33,57.15,11.56,26.77,85.05,65.08,69.60,80.86
6,7,Octen/Octen-Embedding-8B,dense,True,True,True,text,apache-2.0,2025-12-23,14433.0,...,60.28,80.35,66.68,55.68,8.90,25.23,85.12,67.64,71.61,81.27
7,8,codefuse-ai/F2LLM-v2-14B,dense,True,True,True,text,apache-2.0,2026-03-09,53369.0,...,59.45,77.15,73.00,60.91,0.62,28.14,81.26,70.49,66.50,76.97
8,9,codefuse-ai/F2LLM-v2-8B,dense,True,True,True,text,apache-2.0,2026-03-09,28871.0,...,58.99,75.96,71.93,60.62,0.85,27.38,81.18,70.34,66.15,76.47
9,10,microsoft/harrier-oss-v1-0.6b,dense,True,True,True,text,mit,2026-03-27,1137.0,...,59.00,82.85,73.88,54.00,0.81,26.37,82.07,63.16,70.75,77.09
10,11,Bytedance/Seed1.6-embedding-1215,dense,False,True,False,text,NaN,2025-12-15,NaN,...,61.34,78.68,76.75,56.78,-0.02,46.16,85.50,66.24,66.05,75.92
11,12,codefuse-ai/F2LLM-v2-4B,dense,True,True,True,text,apache-2.0,2026-03-09,15344.0,...,58.25,74.49,70.73,59.53,2.25,26.58,80.51,69.38,64.84,75.91
12,13,jinaai/jina-embeddings-v5-omni-small,dense,True,True,True,video; audio; image; text,cc-by-nc-4.0,2026-04-01,3102.0,...,58.90,69.71,71.32,53.41,1.35,41.97,82.93,65.66,64.88,78.85
13,13,jinaai/jina-embeddings-v5-text-small,dense,True,True,True,text,cc-by-nc-4.0,2026-02-17,1137.0,...,58.90,69.71,71.32,53.41,1.35,41.97,82.93,65.66,64.88,78.85
14,15,codefuse-ai/F2LLM-v2-1.7B,dense,True,True,True,text,apache-2.0,2026-03-09,6563.0,...,56.78,73.18,67.68,58.77,0.56,26.04,79.87,67.17,61.97,75.77
15,16,BidirLM/BidirLM-Omni-2.5B-Embedding,dense,True,True,True,video; audio; image; text,apache-2.0,2026-04-07,4663.0,...,55.48,72.29,65.90,51.50,0.97,26.54,80.65,64.72,61.04,75.73
16,17,microsoft/harrier-oss-v1-270m,dense,True,True,True,text,mit,2026-03-27,512.0,...,56.90,81.54,70.84,52.51,-0.47,23.97,80.12,61.90,66.38,75.35
17,18,Qwen/Qwen3-Embedding-0.6B,dense,True,True,True,text,apache-2.0,2025-06-05,1136.0,...,56.01,72.23,66.83,52.33,5.09,24.58,80.83,61.41,64.65,76.17
18,19,jinaai/jina-embeddings-v5-omni-nano,dense,True,True,True,video; audio; image; text,cc-by-nc-4.0,2026-04-01,1881.0,...,57.66,67.70,69.18,52.73,0.05,41.31,81.94,64.63,63.26,78.17
19,19,jinaai/jina-embeddings-v5-text-nano,dense,True,True,True,text,cc-by-nc-4.0,2026-02-17,404.0,...,57.66,67.70,69.18,52.73,0.05,41.31,81.94,64.63,63.26,78.17
20,21,Alibaba-NLP/gte-Qwen2-7B-instruct,dense,True,True,True,text,apache-2.0,2024-06-15,29040.0,...,55.93,73.92,61.55,52.77,4.94,25.48,85.13,65.55,60.08,73.98
21,22,BidirLM/BidirLM-1.7B-Embedding,dense,True,True,True,text,apache-2.0,2026-04-07,3282.0,...,55.39,72.28,66.11,51.82,0.49,26.42,80.23,64.68,62.24,74.25
22,23,Linq-AI-Research/Linq-Embed-Mistral,dense,True,True,True,text,cc-by-nc-4.0,2024-05-29,13563.0,...,NaN,70.34,62.24,50.60,0.94,24.77,80.43,64.37,58.69,NaN
23,24,ICT-TIME-and-Querit/ICT-TIME-and-Querit-embedd...,dense,True,True,True,text,apache-2.0,2026-05-02,7671.0,...,55.02,68.59,67.12,53.04,-0.88,25.49,80.97,62.76,63.99,74.07
24,25,intfloat/multilingual-e5-large-instruct,dense,True,True,True,text,mit,2024-02-08,1068.0,...,55.09,80.13,64.94,50.75,-0.40,22.97,80.86,62.60,57.11,76.81
25,26,BidirLM/BidirLM-1B-Embedding,dense,True,True,True,text,apache-2.0,2026-04-07,1907.0,...,54.84,72.88,66.22,50.04,-0.22,25.15,79.68,63.71,61.61,74.52
26,27,ICT-TIME-and-Querit/BOOM_4B_v1,dense,True,True,True,text,apache-2.0,2026-01-31,7671.0,...,54.81,69.25,66.94,52.80,-0.55,25.41,80.92,61.88,62.21,74.40
27,28,codefuse-ai/F2LLM-v2-0.6B,dense,True,True,True,text,apache-2.0,2026-03-09,2274.0,...,55.02,70.31,64.06,56.58,1.39,25.23,78.95,65.14,59.30,74.22
28,29,google/embeddinggemma-300m,dense,True,True,True,text,gemma,2025-09-04,1155.0,...,54.31,64.40,60.90,51.17,5.61,24.82,81.40,63.25,62.49,74.73
29,30,Salesforce/SFR-Embedding-Mistral,dense,True,True,True,text,cc-by-nc-4.0,2024-01-24,13563.0,...,NaN,70.00,60.02,51.84,0.16,24.55,80.29,64.19,59.44,NaN

In [33]:
benchmark_scores_df = benchmark_scores_df[(~benchmark_scores_df.Clustering.isna()) & (~benchmark_scores_df.Retrieval.isna())].reset_index(drop=True)

In [40]:
benchmark_scores_df

,Rank,Model,Model Type,Open Weights,Instruction Tuned,ST Compatible,Modalities,License,Release Date,Memory (MB),...,Mean (TaskType),BitextMining,Classification,Clustering,InstructionReranking,MultilabelClassification,PairClassification,Reranking,Retrieval,STS
0,1,microsoft/harrier-oss-v1-27b,dense,True,True,True,text,mit,2026-03-27,51515.0,...,64.20,86.02,79.95,58.93,5.39,36.44,85.44,67.35,78.27,79.99
1,2,tencent/KaLM-Embedding-Gemma3-12B-2511,dense,True,True,True,text,NaN,2025-11-06,44884.0,...,62.51,83.76,77.88,55.77,5.49,33.03,84.73,67.27,75.66,79.02
2,3,nvidia/llama-embed-nemotron-8b,dense,True,True,True,text,https://huggingface.co/nvidia/llama-embed-nemo...,2025-10-23,28629.0,...,61.09,81.72,73.21,54.35,10.82,29.86,83.97,67.78,68.69,79.41
3,4,Qwen/Qwen3-Embedding-8B,dense,True,True,True,text,apache-2.0,2025-06-05,14433.0,...,61.69,80.89,74.00,57.65,10.06,28.66,86.40,65.63,70.88,81.08
4,5,google/gemini-embedding-001,dense,False,True,False,text,NaN,2025-07-14,NaN,...,59.59,79.28,71.82,54.59,5.18,29.16,83.63,65.58,67.71,79.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,184,ai-forever/sbert_large_mt_nlu_ru,dense,True,False,True,text,not specified,2021-05-18,1629.0,...,NaN,13.89,40.91,27.07,-0.48,13.71,NaN,34.60,8.47,35.70
154,185,ai-forever/sbert_large_nlu_ru,dense,True,False,True,text,mit,2020-11-20,1629.0,...,NaN,13.22,40.66,27.55,0.56,13.70,NaN,32.13,7.80,30.07
155,186,malenia1/ternary-weight-embedding,dense,True,False,False,text,NaN,2024-10-23,158.0,...,26.58,12.65,38.87,23.89,0.92,12.14,64.88,32.09,10.63,43.16
156,187,jinaai/jina-embeddings-v2-base-en,dense,True,False,True,text,apache-2.0,2023-09-27,262.0,...,NaN,0.90,34.20,21.12,-1.64,10.39,68.24,31.60,10.70,NaN
157,188,mteb/baseline-random-encoder,dense,True,False,False,video; audio; image; text,mit,NaN,0.0,...,15.92,0.38,30.11,21.20,0.45,11.20,52.78,25.14,1.08,0.92

In [35]:
import pandas as pd

cols = ["Clustering", "Retrieval"]

df_borda = benchmark_scores_df.copy()

mask = (
    df_borda["Clustering"].isna()
    | df_borda["Retrieval"].isna()
)

df_borda = (
    df_borda.loc[~mask]
    .reset_index(drop=True)
)

# =====================================================
# GEMINI
# =====================================================
# https://arxiv.org/pdf/2605.27295
nova_linha = {
    "Model": "Gemini 2",
    "Clustering": 55.3,
    "Retrieval": 70.0,
}

df_borda = pd.concat(
    [df_borda, pd.DataFrame([nova_linha])],
    ignore_index=True
)

# =====================================================
# BORDA
# =====================================================

n = len(df_borda)

for col in cols:

    rank = df_borda[col].rank(
        ascending=False,
        method="min"
    )

    df_borda[f"{col}_borda"] = n - rank + 1

df_borda["Borda"] = df_borda[
    [f"{c}_borda" for c in cols]
].sum(axis=1)

# =====================================================
# LOOKUP MTEB
# =====================================================

model_lookup = {}

for m in mteb.get_model_metas():

    model_lookup[m.name] = m.open_weights

    # alguns rankings usam apenas o nome curto
    #model_lookup[m.name.split("/")[-1]] = m.open_weights

# =====================================================
# ABERTO / FECHADO
# =====================================================

df_borda["Aberto"] = (
    df_borda["Model"]
    .map(model_lookup)
)

# Gemini não existe no catálogo MTEB
df_borda.loc[
    df_borda["Model"] == "Gemini 2",
    "Aberto"
] = False

# =====================================================
# EMPRESA / MODELO
# =====================================================

df_borda["Empresa"] = (
    df_borda["Model"]
    .astype(str)
    .str.split("/")
    .str[0]
)

df_borda["Modelo"] = (
    df_borda["Model"]
    .astype(str)
    .str.split("/")
    .str[-1]
)

# =====================================================
# LICENÇA
# =====================================================

df_borda["Licença"] = (
    df_borda["Aberto"]
    .map({
        True: "Aberto",
        False: "Fechado"
    })
)

In [36]:
# =====================================================
# ORDENAÇÃO FINAL
# =====================================================

df_borda = df_borda.sort_values(
    "Borda",
    ascending=False
)

resultado = df_borda[
    [
        "Empresa",
        "Modelo",
        "Licença",
        "Total Params (B)",
        "Clustering",
        "Retrieval",
        "Borda",
    ]
]

resultado = resultado.reset_index(drop=True)
resultado.index = resultado.index + 1

In [43]:
resultado.sort_values("Clustering", ascending=False).head(5)

,Empresa,Modelo,Licença,Total Params (B),Clustering,Retrieval,Borda
3,codefuse-ai,F2LLM-v2-14B,Aberto,13.990,60.91,66.50,309.0
6,codefuse-ai,F2LLM-v2-8B,Aberto,7.568,60.62,66.15,306.0
9,codefuse-ai,F2LLM-v2-4B,Aberto,4.022,59.53,64.84,300.0
1,microsoft,harrier-oss-v1-27b,Aberto,27.009,58.93,78.27,315.0
14,codefuse-ai,F2LLM-v2-1.7B,Aberto,1.721,58.77,61.97,288.0

### resultado.sort_values("Retrieval", ascending=False).head(5)

In [39]:
resultado[resultado["Licença"] == "Fechado"]

,Empresa,Modelo,Licença,Total Params (B),Clustering,Retrieval,Borda
8,Gemini 2,Gemini 2,Fechado,NaN,55.30,70.00,302.0
10,Bytedance,Seed1.6-embedding-1215,Fechado,NaN,56.78,66.05,299.0
12,google,gemini-embedding-001,Fechado,NaN,54.59,67.71,297.0
33,voyageai,voyage-3.5,Fechado,NaN,45.87,64.01,254.0
36,google,text-multilingual-embedding-002,Fechado,NaN,47.84,59.68,247.0
38,openai,text-embedding-3-large,Fechado,NaN,47.05,59.32,243.0
41,Cohere,Cohere-embed-multilingual-v3.0,Fechado,NaN,46.96,59.22,240.0
45,voyageai,voyage-3-lite,Fechado,NaN,44.82,58.60,232.0
54,Cohere,Cohere-embed-multilingual-light-v3.0,Fechado,NaN,44.79,55.79,219.0
61,Cohere,Cohere-embed-english-v3.0,Fechado,NaN,42.32,45.41,192.0
73,Cohere,Cohere-embed-english-light-v3.0,Fechado,NaN,40.40,41.78,165.0

In [38]:
resultado.head(20)

,Empresa,Modelo,Licença,Total Params (B),Clustering,Retrieval,Borda
1,microsoft,harrier-oss-v1-27b,Aberto,27.009,58.93,78.27,315.0
2,Qwen,Qwen3-Embedding-8B,Aberto,7.567,57.65,70.88,310.0
3,codefuse-ai,F2LLM-v2-14B,Aberto,13.990,60.91,66.50,309.0
4,tencent,KaLM-Embedding-Gemma3-12B-2511,Aberto,11.766,55.77,75.66,308.0
5,Octen,Octen-Embedding-8B,Aberto,7.567,55.68,71.61,306.0
6,codefuse-ai,F2LLM-v2-8B,Aberto,7.568,60.62,66.15,306.0
7,Qwen,Qwen3-Embedding-4B,Aberto,4.022,57.15,69.60,306.0
8,Gemini 2,Gemini 2,Fechado,NaN,55.30,70.00,302.0
9,codefuse-ai,F2LLM-v2-4B,Aberto,4.022,59.53,64.84,300.0
10,Bytedance,Seed1.6-embedding-1215,Fechado,NaN,56.78,66.05,299.0
11,microsoft,harrier-oss-v1-0.6b,Aberto,0.596,54.00,70.75,299.0
12,google,gemini-embedding-001,Fechado,NaN,54.59,67.71,297.0
13,nvidia,llama-embed-nemotron-8b,Aberto,7.505,54.35,68.69,297.0
14,codefuse-ai,F2LLM-v2-1.7B,Aberto,1.721,58.77,61.97,288.0
15,jinaai,jina-embeddings-v5-omni-small,NaN,1.626,53.41,64.88,287.0
16,jinaai,jina-embeddings-v5-text-small,Aberto,0.596,53.41,64.88,287.0
17,microsoft,harrier-oss-v1-270m,Aberto,0.268,52.51,66.38,284.0
18,ICT-TIME-and-Querit,ICT-TIME-and-Querit-embedding-v1,NaN,4.022,53.04,63.99,280.0
19,codefuse-ai,F2LLM-v2-0.6B,Aberto,0.596,56.58,59.30,276.0
20,Qwen,Qwen3-Embedding-0.6B,Aberto,0.596,52.33,64.65,276.0