In [1]:
import pandas as pd

In [2]:
mteb = pd.read_csv("../data/mteb.csv")
mteb.head()

,Unnamed: 0,Rank (Borda),Model,Zero-shot,Active Parameters (B),Total Parameters (B),Embedding Dimensions,Max Tokens,Mean (Task),Mean (TaskType),Bitext Mining,Classification,Clustering,Instruction Reranking,Multilabel Classification,Pair Classification,Reranking,Retrieval,STS
0,0,1,[harrier-oss-v1-27b](https://huggingface.co/mi...,78%,25.599,27.009,5376.0,131072.0,74.27,64.20,86.02,79.95,58.93,5.39,36.44,85.44,67.35,78.27,79.99
1,1,2,[KaLM-Embedding-Gemma3-12B-2511](https://huggi...,73%,10.759,11.766,3840.0,32768.0,72.32,62.51,83.76,77.88,55.77,5.49,33.03,84.73,67.27,75.66,79.02
2,2,3,[llama-embed-nemotron-8b](https://huggingface....,99%,6.980,7.505,4096.0,32768.0,69.46,61.09,81.72,73.21,54.35,10.82,29.86,83.97,67.78,68.69,79.41
3,3,4,[Qwen3-Embedding-8B](https://huggingface.co/Qw...,99%,6.946,7.567,4096.0,32768.0,70.58,61.69,80.89,74.00,57.65,10.06,28.66,86.40,65.63,70.88,81.08
4,4,5,[gemini-embedding-001](https://ai.google.dev/g...,99%,NaN,NaN,3072.0,2048.0,68.37,59.59,79.28,71.82,54.59,5.18,29.16,83.63,65.58,67.71,79.40

In [13]:
mteb.sort_values("Clustering", ascending=False).head(20)[["Model", "Clustering"]]

                                                Model  Clustering
7   [F2LLM-v2-14B](https://huggingface.co/codefuse...       60.91
8   [F2LLM-v2-8B](https://huggingface.co/codefuse-...       60.62
11  [F2LLM-v2-4B](https://huggingface.co/codefuse-...       59.53
0   [harrier-oss-v1-27b](https://huggingface.co/mi...       58.93
13  [F2LLM-v2-1.7B](https://huggingface.co/codefus...       58.77
3   [Qwen3-Embedding-8B](https://huggingface.co/Qw...       57.65
5   [Qwen3-Embedding-4B](https://huggingface.co/Qw...       57.15
10  [Seed1.6-embedding-1215](https://console.volce...       56.78
21  [F2LLM-v2-0.6B](https://huggingface.co/codefus...       56.58
1   [KaLM-Embedding-Gemma3-12B-2511](https://huggi...       55.77
6   [Octen-Embedding-8B](https://huggingface.co/Oc...       55.68
35  [F2LLM-v2-330M](https://huggingface.co/codefus...       54.69
4   [gemini-embedding-001](https://ai.google.dev/g...       54.59
2   [llama-embed-nemotron-8b](https://huggingface....       54.35
9   [harrier-oss-v1-0.6b](https://huggingface.co/m...       54.00
33  [SFR-Embedding-2_R](https://huggingface.co/Sal...       53.65
12  [jina-embeddings-v5-text-small](https://huggin...       53.41
22  [BOOM_4B_v1](https://huggingface.co/ICT-TIME-a...       52.80
17  [gte-Qwen2-7B-instruct](https://huggingface.co...       52.77
16  [jina-embeddings-v5-text-nano](https://hugging...       52.73