In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
embeddings = pd.read_parquet("../data/datasets/embeddings_v10.parquet")

In [50]:
embedding_cols = [
    'embedding__codefuse_ai__F2LLM_v2_14B__texto',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado_sem_justificativa',
       'embedding__Octen__Octen_Embedding_8B__texto',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__Qwen__Qwen3_Embedding_8B__texto',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__nvidia__llama_embed_nemotron_8b__texto',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado_sem_justificativa',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado_sem_justificativa',
       'embedding__joaorobson__harrier_oss_v1_27b__texto',
       'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado',
       'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado_sem_justificativa',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado_sem_justificativa',
       'embedding__openai__text_embedding_3_large__trunc8192__texto',
       'embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado',
       'embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado_sem_justificativa',
       'embedding__google__gemini_embedding_2__trunc8192__texto',
       'embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado',
       'embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado_sem_justificativa',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado_sem_justificativa',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado_sem_justificativa',
'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado_sem_justificativa']

In [5]:
for materia in embeddings.materia.unique():
    df_count_temas = embeddings[embeddings.materia == materia]
    total_amostras_materia = len(df_count_temas)  # Total de amostras (linhas) desta matéria
    
    print(f"\n--- Matéria: {materia} ---")
    print(f"Total de amostras (linhas): {total_amostras_materia}")
    
    # Se a matéria não tiver amostras, pula para evitar divisão por zero
    if total_amostras_materia == 0:
        continue
        
    contagem_classes = df_count_temas['tema'].value_counts()
    
    # --- Cenário 1: X >= 2 ---
    # Soma a quantidade de amostras dos temas que aparecem 2 ou mais vezes
    amostras_X2 = contagem_classes[contagem_classes >= 2].sum()
    proporcao_X2 = amostras_X2 / total_amostras_materia
    print(f"Para X >= 2:")
    print(f"  - Qtd de amostras: {amostras_X2}")
    print(f"  - Proporção sobre o total da matéria: {proporcao_X2:.4f} ({proporcao_X2:.2%})")
    
    # --- Cenário 2: X >= 5 ---
    # Soma a quantidade de amostras dos temas que aparecem 5 ou mais vezes
    amostras_X5 = contagem_classes[contagem_classes >= 5].sum()
    proporcao_X5 = amostras_X5 / total_amostras_materia
    print(f"Para X >= 5:")
    print(f"  - Qtd de amostras: {amostras_X5}")
    print(f"  - Proporção sobre o total da matéria: {proporcao_X5:.4f} ({proporcao_X5:.2%})")

--- Matéria: PLP_68_2024 ---
Total de amostras (linhas): 1974
Para X >= 2:
  - Qtd de amostras: 1893
  - Proporção sobre o total da matéria: 0.9590 (95.90%)
Para X >= 5:
  - Qtd de amostras: 1679
  - Proporção sobre o total da matéria: 0.8506 (85.06%)

--- Matéria: MPV_612_2013 ---
Total de amostras (linhas): 220
Para X >= 2:
  - Qtd de amostras: 179
  - Proporção sobre o total da matéria: 0.8136 (81.36%)
Para X >= 5:
  - Qtd de amostras: 157
  - Proporção sobre o total da matéria: 0.7136 (71.36%)

--- Matéria: PEC_6_2019 ---
Total de amostras (linhas): 268
Para X >= 2:
  - Qtd de amostras: 264
  - Proporção sobre o total da matéria: 0.9851 (98.51%)
Para X >= 5:
  - Qtd de amostras: 245
  - Proporção sobre o total da matéria: 0.9142 (91.42%)

In [6]:
def extrair_tipo_texto(col):

    if col.endswith("__texto_preprocessado_sem_justificativa"):
        return "texto_preprocessado_sem_justificativa"

    if col.endswith("__texto_preprocessado"):
        return "texto_preprocessado"

    if col.endswith("__texto"):
        return "texto"

    return "outro"

In [95]:
import numpy as np

# Seus dados da biblioteca
data = retriever.scores["data"]
indices = retriever.scores["indices"]
indptr = retriever.scores["indptr"]
nonoccurrence_array = retriever.nonoccurrence_array

# 1. Descobrir qual "termo" (coluna) corresponde a cada índice do array `data`
term_indices = np.zeros_like(data, dtype=np.int32)
for i in range(len(indptr) - 1):
    start, end = indptr[i], indptr[i+1]
    term_indices[start:end] = i

# 2. Somar o nonoccurrence correspondente de volta (Scores originais reconstruídos)
scores_originais = data + nonoccurrence_array[term_indices]

# -------------------------------------------------------------
# 3. CONSTRUÇÃO DA MATRIZ DENSA (Documentos x Termos)
# -------------------------------------------------------------
num_docs = retriever.scores["num_docs"]  # ou len(corpus)
num_terms = len(nonoccurrence_array)

# Criamos uma matriz cheia de zeros com o tamanho correto (Docs x Termos)
matriz_densa = np.zeros((num_docs, num_terms), dtype=np.float32)

# Como a estrutura do bm25s armazena os dados onde:
# `indices` são os IDs dos documentos correspondentes a cada score em `data`
doc_indices = indices 

# Preenchemos a matriz usando indexação avançada do NumPy
matriz_densa[doc_indices, term_indices] = scores_originais

# Converter para lista de listas do Python para o seu formato exato
resultado_final = matriz_densa.tolist()

print(resultado_final)

[[1.189976692199707, 1.189976692199707, 1.189976692199707, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.189976692199707, 1.189976692199707, 1.189976692199707, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.313610553741455, 1.313610553741455]]

In [109]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix

# Seus dados da biblioteca
data = retriever.scores["data"]
indices = retriever.scores["indices"]
indptr = retriever.scores["indptr"]
nonoccurrence_array = retriever.nonoccurrence_array

# 1. Descobrir qual "termo" (coluna) corresponde a cada índice do array `data`
term_indices = np.zeros_like(data, dtype=np.int32)
for i in range(len(indptr) - 1):
    start, end = indptr[i], indptr[i+1]
    term_indices[start:end] = i

# 2. Somar o nonoccurrence correspondente de volta (Scores originais reconstruídos)
scores_originais = data + nonoccurrence_array[term_indices]

# -------------------------------------------------------------
# 3. CONSTRUÇÃO DA MATRIZ ESPARSA IGUAL AO TFIDFVECTORIZER
# -------------------------------------------------------------
num_docs = retriever.scores["num_docs"]
num_terms = len(nonoccurrence_array)

# Primeiro, recriamos a estrutura esparsa original reconstruída (formato CSC: Termos x Docs)
matriz_csc = csc_matrix((scores_originais, indices, indptr), shape=(num_docs, num_terms))

# O TfidfVectorizer entrega uma matriz CSR orientada a Documentos x Vocabulário (D x V)
# Para fazer isso, precisamos transpor (.T) a matriz CSC, o que automaticamente a converte para CSR!
matriz_estilo_tfidf = matriz_csc.T.tocsr()

# -------------------------------------------------------------
# Pronto! O objeto 'matriz_estilo_tfidf' é idêntico ao output do scikit-learn
# -------------------------------------------------------------
print(type(matriz_estilo_tfidf))  # <class 'scipy.sparse._csr.csr_matrix'>
print(matriz_estilo_tfidf.shape)  # (num_docs, num_terms)

<class 'scipy.sparse._csr.csr_matrix'>
(8, 3)

In [8]:
import numpy as np
import bm25s
from scipy.sparse import csr_matrix
from sklearn.base import BaseEstimator, TransformerMixin

import numpy as np
import bm25s
from scipy.sparse import csr_matrix
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import normalize

class BM25LVectorizer(BaseEstimator, TransformerMixin):
    def __init__(self, k1=1.5, b=0.75, delta=0.5, norm="l2"):
        self.k1 = k1
        self.b = b
        self.delta = delta
        self.norm = norm
        self.retriever = None
        self.vocabulary_ = None
        self._old_to_new_cols = None  # Mapeamento para reordenar as colunas no transform
        
    def fit(self, X, y=None):
        """
        Aprende o vocabulário e calcula as estatísticas do BM25L sobre o corpus.
        """
        # Força tokenização limpa por split (removendo strings vazias acidentais)
        corpus_tokens = [[w for w in doc.split() if w != ''] for doc in X]
        
        # Inicializa e indexa o retriever do bm25s
        self.retriever = bm25s.BM25(
            method="bm25l",
            k1=self.k1,
            b=self.b,
            delta=self.delta,
            corpus=corpus_tokens
        )
        self.retriever.index(corpus_tokens, show_progress=False)
        
        # 1. Recupera o dicionário de vocabulário original da biblioteca
        vocab_original = {term: idx for term, idx in self.retriever.vocab_dict.items() if term != ''}

        # 2. Cria o novo vocabulário ordenado alfabeticamente (Estilo Sklearn)
        termos_ordenados = sorted(vocab_original.keys())
        self.vocabulary_ = {term: idx for idx, term in enumerate(termos_ordenados)}
        
        # 3. Cria um array mapeando qual coluna nova alfabética corresponde a cada coluna original da lib
        # Ex: se o termo na coluna original 0 deve ir para a coluna nova 5, o array na posição 0 terá o valor 5
        self._old_to_new_cols = np.array([self.vocabulary_[term] for term in vocab_original.keys()])
        
        return self

    def transform(self, X):
        """
        Transforma os documentos na matriz esparsa CSR do sklearn (Documentos x Vocabulário Ordenado)
        com os scores originais reconstruídos.
        """
        if self.retriever is None:
            raise RuntimeError("O vetorizador precisa ser ajustado com 'fit' antes de transformar.")
            
        data = self.retriever.scores["data"]
        indices = self.retriever.scores["indices"]
        indptr = self.retriever.scores["indptr"]
        nonoccurrence_array = self.retriever.nonoccurrence_array
        
        num_docs = self.retriever.scores["num_docs"]
        num_terms = len(self.vocabulary_)

        # 1. Reconstrói os scores originais (Reversão do Shifting)
        term_indices = np.zeros_like(data, dtype=np.int32)
        for i in range(len(indptr) - 1):
            start, end = indptr[i], indptr[i+1]
            term_indices[start:end] = i

        scores_originais = data + nonoccurrence_array[term_indices]

        # 2. Monta a matriz bruta respeitando o indptr da biblioteca (Termos x Documentos)
        # Isso evita o erro de ValueError: index pointer size
        matriz_raw = csr_matrix((scores_originais, indices, indptr), shape=(num_terms, num_docs))
        
        # 3. Transpõe (.T) para virar a estrutura padrão do sklearn (Documentos x Termos)
        matriz_csr = matriz_raw.T.tocsr()
        
        # 4. FIX: Reordena as colunas de acordo com a ordem alfabética do vocabulary_
        # np.argsort nos dá os índices necessários para ordenar as colunas corretamente
        sorting_order = np.argsort(self._old_to_new_cols)
        matriz_csr = matriz_csr[:, sorting_order]
        if self.norm is not None:
            # axis=1 garante que a normalização aconteça por linha (documento)
            # copy=False altera os dados in-place para máxima eficiência de memória
            matriz_csr = normalize(matriz_csr, norm=self.norm, axis=1, copy=False)
        return matriz_csr

    def fit_transform(self, X, y=None):
        """
        Ajusta aos dados e retorna a matriz de termos modificada.
        """
        return self.fit(X, y).transform(X)

In [9]:
bm25l_vectorizer = BM25LVectorizer()
corpus = [
    "a cat is a feline and likes to purr",
    "a dog is the human's best friend and loves to play",
    "a bird is a beautiful animal that can fly",
]
bm25l_vectorizer.fit_transform(corpus).toarray()

array([[0.08001116, 0.22572611, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.47105756, 0.        , 0.47105756,
        0.        , 0.        , 0.        , 0.0641304 , 0.47105756,
        0.        , 0.        , 0.47105756, 0.        , 0.        ,
        0.22572611],
       [0.049724  , 0.17501847, 0.        , 0.        , 0.3652381 ,
        0.        , 0.        , 0.        , 0.3652381 , 0.        ,
        0.        , 0.3652381 , 0.3652381 , 0.049724  , 0.        ,
        0.3652381 , 0.3652381 , 0.        , 0.        , 0.3652381 ,
        0.17501847],
       [0.06907053, 0.        , 0.40664572, 0.40664572, 0.        ,
        0.40664572, 0.40664572, 0.        , 0.        , 0.        ,
        0.40664572, 0.        , 0.        , 0.05536128, 0.        ,
        0.        , 0.        , 0.        , 0.40664572, 0.        ,
        0.        ]], dtype=float32)

In [10]:
import math
from collections import Counter

# ------------------------
# TF
# ------------------------
def tf(doc, term):
    return doc.split().count(term)

# ------------------------
# DF
# ------------------------
def df(corpus, term):
    return sum(1 for doc in corpus if term in doc.split())

# ------------------------
# IDF (compatível com lib BM25)
# ------------------------
def idf(corpus, term):
    N = len(corpus)
    df_t = df(corpus, term)
    #print('df', df_t)
    #print(math.log((N + 1) / (df_t + 0.5)))
    return math.log((N + 1) / (df_t + 0.5))

# ------------------------
# BM25L score (versão da lib)
# ------------------------


def bm25l_score(corpus, doc, term, avg_dl, k1=1.5, b=0.75, delta=0.5):
    tf_t = tf(doc, term)
    dl = len(doc.split())

    if tf_t == 0:
        return 0.0

    # O delta DEVE somar direto no c(d,t) de acordo com a definição do BM25L
    c_dt = (tf_t / (1 - b + b * dl / avg_dl)) + delta

    # Agora o BM25L TF component usa o c_dt corrigido
    tfc = ((k1 + 1) * c_dt) / (k1 + c_dt)
    
    return idf(corpus, term) * tfc

# ------------------------
# Matrix BM25L
# ------------------------
corpus = [
    "a cat is a feline and likes to purr",
    "a dog is the human's best friend and loves to play",
    "a bird is a beautiful animal that can fly",
]

vocab = sorted(set(w for doc in corpus for w in doc.split()))
avg_dl = sum(len(d.split()) for d in corpus) / len(corpus)

matrix = []

for doc in corpus:
    row = []
    for term in vocab:
        row.append(bm25l_score(corpus, doc, term, avg_dl))
    matrix.append(row)

print(matrix)
print(len(matrix[0]))

[[0.21196631461967907, 0.5979956889956903, 0.0, 0.0, 0.0, 0.0, 0.0, 1.2479300763765264, 0.0, 1.2479300763765264, 0.0, 0.0, 0.0, 0.16989485222316486, 1.2479300763765264, 0.0, 0.0, 1.2479300763765264, 0.0, 0.0, 0.5979956889956903], [0.16152991043289022, 0.5685527773133899, 0.0, 0.0, 1.186486999610959, 0.0, 0.0, 0.0, 1.186486999610959, 0.0, 0.0, 1.186486999610959, 1.186486999610959, 0.16152991043289022, 0.0, 1.186486999610959, 1.186486999610959, 0.0, 0.0, 1.186486999610959, 0.5685527773133899], [0.21196631461967907, 0.0, 1.2479300763765264, 1.2479300763765264, 0.0, 1.2479300763765264, 1.2479300763765264, 0.0, 0.0, 0.0, 1.2479300763765264, 0.0, 0.0, 0.16989485222316486, 0.0, 0.0, 0.0, 0.0, 1.2479300763765264, 0.0, 0.0]]
21

In [14]:
# ------------------------
# Novo Corpus de Teste
# ------------------------
corpus_teste = embeddings.texto_preprocessado_sem_justificativa.values[:100]

# 1. Executa na sua classe customizada
bm25l_vectorizer = BM25LVectorizer(norm=None)
matriz_classe = bm25l_vectorizer.fit_transform(corpus_teste).toarray()

# 2. Executa no seu loop manual antigo para validação
vocab = sorted(set(w for doc in corpus_teste for w in doc.split()))
avg_dl = sum(len(d.split()) for d in corpus_teste) / len(corpus_teste)

matrix_loop = []
for doc in corpus_teste:
    row = []
    for term in vocab:
        row.append(bm25l_score(corpus_teste, doc, term, avg_dl))
    matrix_loop.append(row)

# ------------------------
# Validação Automatizada
# ------------------------
print(f"Tamanho do vocabulário: {len(vocab)} termos")
print(f"Shape da matriz da classe: {matriz_classe.shape}")

# Compara as duas matrizes tolerando as diferenças float32 vs float64
sao_iguais = np.allclose(matriz_classe, matrix_loop, atol=1e-5)
print(f"\n As duas matrizes são idênticas? {sao_iguais}")

if not sao_iguais:
    print("\nOps, houve divergência em algum ponto!")
else:
    print("\nSucesso total! A classe manteve a consistência perfeita.")

zzzzz

In [36]:
import math
from collections import Counter

# ------------------------
# TF
# ------------------------
def tf(doc, term):
    tokens = doc.split()
    return tokens.count(term)

# ------------------------
# DF
# ------------------------
def df(corpus, term):
    return sum(1 for doc in corpus if term in doc.split())

# ------------------------
# IDF (versão padrão suavizada)
# ------------------------
def idf(corpus, term):
    N = len(corpus)
    return math.log((N + 1) / (df(corpus, term) + 1)) + 1

# ------------------------
# TF-IDF
# ------------------------
def tfidf(corpus, doc, term):
    return tf(doc, term) * idf(corpus, term)

corpus = [
    "1 2 3",
    "2 3 4",
    "5"
]
vocab = sorted(set(word for doc in corpus for word in doc.split()))
matrix = []
for doc in corpus:
    row = []
    
    for term in vocab:
        value = tf(doc, term) * idf(corpus, term)
        row.append(value)
    
    matrix.append(row)
print(matrix)

[[1.6931471805599454, 1.2876820724517808, 1.2876820724517808, 0.0, 0.0], [0.0, 1.2876820724517808, 1.2876820724517808, 1.6931471805599454, 0.0], [0.0, 0.0, 0.0, 0.0, 1.6931471805599454]]

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Corpus de exemplo
corpus = [
    "1 2 3",
    "2 3 4",
    "5",
]

# Vetorizador TF-IDF
vectorizer = TfidfVectorizer(token_pattern=r"(?u)\b\w+\b", norm=None)

# Ajusta e transforma o corpus
X = vectorizer.fit_transform(corpus)

# Matriz TF-IDF (sparse)
print(X.shape)

# Nomes das features (termos)
print(vectorizer.get_feature_names_out())

# Converter para array (opcional)
print(X.toarray())

(3, 5)
['1' '2' '3' '4' '5']
[[1.69314718 1.28768207 1.28768207 0.         0.        ]
 [0.         1.28768207 1.28768207 1.69314718 0.        ]
 [0.         0.         0.         0.         1.69314718]]

In [51]:
import gc
import numpy as np
import pandas as pd

from scipy.sparse import load_npz

from sklearn.cluster import (
    AgglomerativeClustering
)
from sklearn.metrics import (
    adjusted_rand_score,
    v_measure_score
)
from sklearn.preprocessing import normalize

from tqdm import tqdm


# =========================
# CONFIG
# =========================

materias = [
    "PEC_6_2019",
    "MPV_612_2013",
    "PLP_68_2024"
]


# =========================
# BM25L
# =========================

bm25_matrices_raw = {
    "texto": load_npz(
        "../data/bm25l/bm25l_texto_raw.npz"
    ),
    "texto_preprocessado": load_npz(
        "../data/bm25l/bm25l_texto_preprocessado_raw.npz"
    ),
    "texto_preprocessado_sem_justificativa": load_npz(
        "../data/bm25l/bm25l_texto_preprocessado_sem_justificativa_raw.npz"
    ),
}

bm25_matrices_preprocess = {
    "texto": load_npz(
        "../data/bm25l/bm25l_texto_preprocess.npz"
    ),
    "texto_preprocessado": load_npz(
        "../data/bm25l/bm25l_texto_preprocessado_preprocess.npz"
    ),
    "texto_preprocessado_sem_justificativa": load_npz(
        "../data/bm25l/bm25l_texto_preprocessado_sem_justificativa_preprocess.npz"
    ),
}


# =========================
# REPRESENTAÇÕES
# =========================

sparse_representations = {}

for nome, X in bm25_matrices_raw.items():
    sparse_representations[
        f"bm25l_raw__{nome}"
    ] = X

for nome, X in bm25_matrices_preprocess.items():
    sparse_representations[
        f"bm25l_preprocess__{nome}"
    ] = X


# =========================
# MODELOS
# =========================

def get_models(n_clusters):

    return {
        "agglomerative": AgglomerativeClustering(
            n_clusters=n_clusters,
            metric="cosine",
            linkage="average"
        ),
    }


# =========================
# LOOP PRINCIPAL
# =========================

resultados = {}
resultados_df = {}

for materia in materias:

    print(f"\n{'='*80}")
    print(f"Processando {materia}")
    print(f"{'='*80}")

    df_materia = (
        embeddings[
            embeddings["materia"] == materia
        ]
        .copy()
    )

    niveis = ["tema"]

    if materia == "PLP_68_2024":
        niveis = [
            "tema_macro",
            "tema_nivel_2",
            "tema",
        ]

    resultados[materia] = []

    idx = df_materia.index

    # ==================================================
    # CACHE DOS EMBEDDINGS
    # ==================================================

    print("Normalizando embeddings...")

    dense_cache = {}

    for emb_col in tqdm(
        embedding_cols,
        desc="Embeddings cache"
    ):

        dense_cache[emb_col] = normalize(
            np.vstack(
                df_materia[emb_col].values
            ).astype(np.float32)
        )

    # ==================================================
    # CACHE BM25 (MANTÉM ESPARSO)
    # ==================================================

    print("Preparando BM25...")

    sparse_cache = {}

    for nome, X_full in tqdm(
        sparse_representations.items(),
        desc="BM25 cache"
    ):

        sparse_cache[nome] = normalize(
            X_full[idx]
        ).astype(np.float32)

    # ==================================================
    # NÍVEIS
    # ==================================================

    for nivel in niveis:

        y_true = (
            df_materia[nivel]
            .fillna("")
            .astype(str)
            .values
        )

        n_clusters = len(
            np.unique(y_true)
        )

        print(
            f"\nNivel={nivel} | "
            f"Clusters={n_clusters}"
        )

        # ==================================================
        # EMBEDDINGS DENSOS
        # ==================================================

        for emb_col in tqdm(
            embedding_cols,
            desc=f"{nivel} | Embeddings"
        ):

            X = dense_cache[emb_col]

            for (
                model_name,
                model
            ) in get_models(
                n_clusters
            ).items():

                y_pred = model.fit_predict(X)

                resultados[materia].append({
                    "nivel": nivel,
                    "embedding": emb_col,
                    "modelo": model_name,
                    "ari": adjusted_rand_score(
                        y_true,
                        y_pred
                    ),
                    "v_measure": v_measure_score(
                        y_true,
                        y_pred
                    ),
                })

                del y_pred

        gc.collect()

        # ==================================================
        # BM25
        # ==================================================

        for (
            nome,
            X_sparse
        ) in tqdm(
            sparse_cache.items(),
            desc=f"{nivel} | BM25"
        ):

            # ------------------------------------------
            # AGGLOMERATIVE
            # ------------------------------------------

            X_dense = X_sparse.toarray()

            agglomerative = (
                AgglomerativeClustering(
                    n_clusters=n_clusters,
                    metric="cosine",
                    linkage="average"
                )
            )

            y_pred = agglomerative.fit_predict(
                X_dense
            )

            resultados[materia].append({
                "nivel": nivel,
                "embedding": nome,
                "modelo": "agglomerative",
                "ari": adjusted_rand_score(
                    y_true,
                    y_pred
                ),
                "v_measure": v_measure_score(
                    y_true,
                    y_pred
                ),
            })

            del y_pred
            del agglomerative
            del X_dense

            gc.collect()

        gc.collect()

    # ==================================================
    # RESULTADOS
    # ==================================================

    resultados_df[materia] = (
        pd.DataFrame(
            resultados[materia]
        )
        .sort_values(
            ["ari", "v_measure"],
            ascending=False
        )
        .reset_index(drop=True)
    )

    display(
        resultados_df[materia]
        .head(20)
    )

    # ==================================================
    # LIMPEZA
    # ==================================================

    del dense_cache
    del sparse_cache

    gc.collect()

================================================================================
Processando PEC_6_2019
================================================================================
Normalizando embeddings...

Embeddings cache: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 75.47it/s]

Preparando BM25...

BM25 cache: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 285.69it/s]

Nivel=tema | Clusters=29

tema | Embeddings: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:04<00:00, 10.40it/s]
tema | BM25: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:26<00:00,  4.37s/it]

,nivel,embedding,modelo,ari,v_measure
0,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,agglomerative,0.528830,0.786561
1,tema,embedding__joaorobson__harrier_oss_v1_27b__texto,agglomerative,0.502200,0.786200
2,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,agglomerative,0.466991,0.780961
3,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,agglomerative,0.452424,0.756060
4,tema,embedding__Qwen__Qwen3_Embedding_8B__texto,agglomerative,0.440935,0.767465
5,tema,embedding__Octen__Octen_Embedding_8B__texto,agglomerative,0.433797,0.768525
6,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,agglomerative,0.416230,0.748648
7,tema,embedding__ICT_TIME_and_Querit__ICT_TIME_and_Q...,agglomerative,0.371214,0.717290
8,tema,embedding__jinaai__jina_embeddings_v5_text_sma...,agglomerative,0.365572,0.707838
9,tema,embedding__nvidia__llama_embed_nemotron_8b__te...,agglomerative,0.360503,0.693100
10,tema,embedding__openai__text_embedding_3_large__tru...,agglomerative,0.348803,0.707559
11,tema,embedding__jinaai__jina_embeddings_v5_text_sma...,agglomerative,0.343582,0.699583
12,tema,embedding__josedossantos__bertimbau_tuned__tru...,agglomerative,0.295309,0.631177
13,tema,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,agglomerative,0.280942,0.654282
14,tema,bm25l_preprocess__texto_preprocessado,agglomerative,0.270408,0.609462
15,tema,embedding__openai__text_embedding_3_large__tru...,agglomerative,0.267854,0.579002
16,tema,bm25l_raw__texto_preprocessado,agglomerative,0.265479,0.605082
17,tema,embedding__josedossantos__bertimbau_tuned__mea...,agglomerative,0.257204,0.626152
18,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto,agglomerative,0.254173,0.584464
19,tema,embedding__nvidia__llama_embed_nemotron_8b__texto,agglomerative,0.245558,0.619179

================================================================================
Processando MPV_612_2013
================================================================================
Normalizando embeddings...

Embeddings cache: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 71.64it/s]

Preparando BM25...

BM25 cache: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 666.08it/s]

Nivel=tema | Clusters=58

tema | Embeddings: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:03<00:00, 13.54it/s]
tema | BM25: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:19<00:00,  3.18s/it]

,nivel,embedding,modelo,ari,v_measure
0,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,agglomerative,0.277524,0.714753
1,tema,embedding__ICT_TIME_and_Querit__ICT_TIME_and_Q...,agglomerative,0.255449,0.719338
2,tema,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,agglomerative,0.254482,0.708883
3,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,agglomerative,0.241417,0.710784
4,tema,embedding__Qwen__Qwen3_Embedding_8B__texto,agglomerative,0.236870,0.683678
5,tema,embedding__openai__text_embedding_3_large__tru...,agglomerative,0.234123,0.721221
6,tema,embedding__google__gemini_embedding_2__trunc81...,agglomerative,0.229528,0.695871
7,tema,bm25l_preprocess__texto_preprocessado,agglomerative,0.224040,0.711967
8,tema,embedding__openai__text_embedding_3_large__tru...,agglomerative,0.220633,0.707353
9,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto,agglomerative,0.214929,0.663390
10,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,agglomerative,0.208311,0.690072
11,tema,embedding__joaorobson__harrier_oss_v1_27b__texto,agglomerative,0.205328,0.691960
12,tema,embedding__nvidia__llama_embed_nemotron_8b__te...,agglomerative,0.201859,0.703833
13,tema,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,agglomerative,0.191741,0.699121
14,tema,bm25l_raw__texto_preprocessado,agglomerative,0.185694,0.688855
15,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,agglomerative,0.182111,0.686624
16,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,agglomerative,0.175308,0.674323
17,tema,embedding__google__gemini_embedding_2__trunc81...,agglomerative,0.174140,0.653325
18,tema,embedding__Octen__Octen_Embedding_8B__texto,agglomerative,0.172873,0.691535
19,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,agglomerative,0.171193,0.687444

================================================================================
Processando PLP_68_2024
================================================================================
Normalizando embeddings...

Embeddings cache: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:05<00:00,  8.90it/s]

Preparando BM25...

BM25 cache: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 83.33it/s]

Nivel=tema_macro | Clusters=35

tema_macro | Embeddings: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [05:00<00:00,  6.26s/it]
tema_macro | BM25: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [25:53<00:00, 258.84s/it]

Nivel=tema_nivel_2 | Clusters=102

tema_nivel_2 | Embeddings: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [03:33<00:00,  4.44s/it]
tema_nivel_2 | BM25: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [20:24<00:00, 204.12s/it]

Nivel=tema | Clusters=261

tema | Embeddings: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [03:31<00:00,  4.41s/it]
tema | BM25: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [20:52<00:00, 208.69s/it]

,nivel,embedding,modelo,ari,v_measure
0,tema_nivel_2,bm25l_preprocess__texto_preprocessado_sem_just...,agglomerative,0.492454,0.766232
1,tema_nivel_2,embedding__joaorobson__harrier_oss_v1_27b__texto,agglomerative,0.441133,0.755717
2,tema_nivel_2,bm25l_preprocess__texto_preprocessado,agglomerative,0.424448,0.750624
3,tema_nivel_2,embedding__openai__text_embedding_3_large__tru...,agglomerative,0.422598,0.734089
4,tema_nivel_2,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,agglomerative,0.419625,0.732944
5,tema_nivel_2,bm25l_preprocess__texto,agglomerative,0.419169,0.739557
6,tema_nivel_2,embedding__joaorobson__harrier_oss_v1_27b__tex...,agglomerative,0.417927,0.742535
7,tema,embedding__Octen__Octen_Embedding_8B__texto,agglomerative,0.395666,0.831479
8,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,agglomerative,0.395632,0.832587
9,tema_nivel_2,embedding__Qwen__Qwen3_Embedding_8B__texto,agglomerative,0.389375,0.732752
10,tema,embedding__joaorobson__harrier_oss_v1_27b__texto,agglomerative,0.387976,0.829588
11,tema_nivel_2,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,agglomerative,0.381176,0.735811
12,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,agglomerative,0.379683,0.826861
13,tema,bm25l_preprocess__texto_preprocessado_sem_just...,agglomerative,0.376505,0.828287
14,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,agglomerative,0.376096,0.827747
15,tema_nivel_2,bm25l_raw__texto_preprocessado,agglomerative,0.372976,0.712967
16,tema_nivel_2,embedding__jinaai__jina_embeddings_v5_text_sma...,agglomerative,0.365595,0.713637
17,tema,embedding__Qwen__Qwen3_Embedding_8B__texto,agglomerative,0.365512,0.822778
18,tema_nivel_2,embedding__Octen__Octen_Embedding_8B__texto_pr...,agglomerative,0.363712,0.724959
19,tema,bm25l_preprocess__texto_preprocessado,agglomerative,0.362855,0.812981

In [63]:
df_all = pd.concat(
    [
        df.assign(
            materia=materia,
            tipo_texto=df["embedding"].apply(extrair_tipo_texto)
        )
        for materia, df in resultados_df.items()
    ],
    ignore_index=True
)

In [57]:
df_clustering

,nivel,embedding,modelo,ari,v_measure,materia,tipo_texto
0,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,agglomerative,0.528830,0.786561,PEC_6_2019,texto_preprocessado
1,tema,embedding__joaorobson__harrier_oss_v1_27b__texto,agglomerative,0.502200,0.786200,PEC_6_2019,texto
2,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,agglomerative,0.466991,0.780961,PEC_6_2019,texto_preprocessado
3,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,agglomerative,0.452424,0.756060,PEC_6_2019,texto_preprocessado
4,tema,embedding__Qwen__Qwen3_Embedding_8B__texto,agglomerative,0.440935,0.767465,PEC_6_2019,texto
...,...,...,...,...,...,...,...
265,tema,embedding__PORTULAN__serafim_335m_portuguese_p...,agglomerative,0.022133,0.562225,PLP_68_2024,texto_preprocessado
266,tema_nivel_2,embedding__PORTULAN__serafim_335m_portuguese_p...,agglomerative,0.020542,0.425307,PLP_68_2024,texto
267,tema,embedding__PORTULAN__serafim_335m_portuguese_p...,agglomerative,0.019804,0.543635,PLP_68_2024,texto
268,tema_nivel_2,embedding__PORTULAN__serafim_335m_portuguese_p...,agglomerative,0.018159,0.374672,PLP_68_2024,texto
269,tema_macro,embedding__Octen__Octen_Embedding_8B__texto_pr...,agglomerative,0.004350,0.250027,PLP_68_2024,texto_preprocessado_sem_justificativa

In [58]:
#df_clustering.to_parquet("../data/datasets/resultados_clustering.parquet", index=False)

In [59]:
import re

def map_latex_names(df, column="embedding"):
    """
    Mapeia nomes longos de embeddings/retrieval para nomes curtos de tabela LaTeX.
    
    Parameters
    ----------
    df : pd.DataFrame
        DataFrame com coluna de embeddings/retrieval
    column : str
        Nome da coluna que contém os identificadores longos
    
    Returns
    -------
    pd.Series
        Série com nomes mapeados para LaTeX
    """

    mapping_rules = [
        (r".*bm25l.*raw.*", "BM25L"),
        (r".*bm25l.*preprocess.*", "BM25L (prep)"),
        
        (r".*Octen.*", "OCTEN"),
        (r".*ICT_TIME_and_Querit.*", "ICTT"),
        (r".*F2LLM.*", "F2LLM"),
        (r".*harrier.*", "HARRIER"),
        (r".*KaLM.*", "KALM"),
        (r".*nemo.*", "NEMO"),
        (r".*Qwen3.*", "QWEN3"),
        (r".*gemini_embedding_2.*", "GOOGLE"),
        (r".*text_embedding_3_large.*", "OPENAI"),
        (r".*jina_embeddings_v5.*clustering.*", "JINA (clust)"),
        (r".*jina_embeddings_v5.*text_matching.*", "JINA (text-m)"),
        (r".*bertimbau.*meanpool.*", "BERT (mp)"),
        (r".*bertimbau.*trunc.*", "BERT (trunc)"),
        (r".*serafim_335m_portuguese_pt_sentence_encoder__.*meanpool.*", "SRFB (mp)"),
        (r".*serafim_335m_portuguese_pt_sentence_encoder__.*trunc.*", "SRFB (trunc)"),
        (r".*serafim_335m_portuguese_pt_sentence_encoder_ir.*meanpool.*", "SRFIR (mp)"),
        (r".*serafim_335m_portuguese_pt_sentence_encoder_ir.*trunc.*", "SRFIR (trunc)"),
    ]

    def _map_name(name):
        for pattern, latex_name in mapping_rules:
            if re.match(pattern, name, re.IGNORECASE):
                return latex_name
        return name  # fallback

    return df[column].apply(_map_name)

In [64]:
df_all["nome_latex"] =  map_latex_names(df_clustering)

In [67]:
import gc
import scipy.stats as stats
import pandas as pd
import numpy as np

# =====================================================================
# 1. CONSOLIDAÇÃO DAS ESTATÍSTICAS DESCRITIVAS (MÉDIA E DESVIO PADRÃO)
# =====================================================================
print("--- Calculando Média e Desvio Padrão por Tratamento ---")

print("\n" + "="*70)
print("INICIANDO ANÁLISE ESTATÍSTICA COMPLETA")
print("="*70)
metricas = ["ari", "v_measure"]
# =====================================================================
# 2. CONSOLIDAÇÃO DAS ESTATÍSTICAS DESCRITIVAS (MÉDIA E DESVIO PADRÃO)
# =====================================================================
print("\n--- 1. Calculando Média e Desvio Padrão por Tratamento ---")

df_estatisticas = (
    df_all[df_all["nivel"] == "tema"]
    .groupby(["materia", "tipo_texto"])[metricas]
    .agg(["mean", "std"])
)

# Simplifica o multi-index das colunas para 'metrica_mean' e 'metrica_std'
df_estatisticas.columns = [f"{metric}_{stat}" for metric, stat in df_estatisticas.columns]
display(df_estatisticas)


# =====================================================================
# 3. TESTES DE SIGNIFICÂNCIA ESTATÍSTICA (MELHORA EM RELAÇÃO AO BRUTO)
# =====================================================================
print("\n--- 2. Executando Testes de Wilcoxon (Melhora vs. Bruto) ---")

# Filtra apenas o nível 'tema'
df_filtrado = df_all[df_all["nivel"] == "tema"].copy()
lista_materias = df_filtrado["materia"].unique()
registros_testes = []

for materia in lista_materias:
    df_mat = df_filtrado[df_filtrado["materia"] == materia]
    
    # Isola o baseline fixo: Texto Bruto
    df_bruto = df_mat[df_mat["tipo_texto"] == "texto"]
    
    if df_bruto.empty:
        print(f"[Aviso] Matéria {materia} não possui dados para o tipo 'texto' (Bruto).")
        continue
        
    for metric in metricas:
        # Vetor de pontuações do Baseline Bruto (tamanho 10, um para cada modelo)
        scores_bruto = df_bruto.sort_values("embedding")[metric].values
        
        # -----------------------------------------------------------------
        # Teste 1: Pré-processado COMPLETO (Alt. + Just.) SUPEROU o Bruto?
        # -----------------------------------------------------------------
        df_alt_just = df_mat[df_mat["tipo_texto"] == "texto_preprocessado"]
        if not df_alt_just.empty:
            scores_alt_just = df_alt_just.sort_values("embedding")[metric].values
            
            if len(scores_alt_just) == len(scores_bruto):
                # 'greater' testa se: scores_alt_just > scores_bruto
                _, p_val_alt_just = stats.wilcoxon(scores_alt_just, scores_bruto, alternative="greater")
            else:
                p_val_alt_just = np.nan
        else:
            p_val_alt_just = np.nan
            
        # -----------------------------------------------------------------
        # Teste 2: Pré-processado SEM Justificativa (Alt. Pura) SUPEROU o Bruto?
        # -----------------------------------------------------------------
        df_sem_j = df_mat[df_mat["tipo_texto"] == "texto_preprocessado_sem_justificativa"]
        if not df_sem_j.empty:
            scores_sem_j = df_sem_j.sort_values("embedding")[metric].values
            
            if len(scores_sem_j) == len(scores_bruto):
                # 'greater' testa se: scores_sem_j > scores_bruto
                _, p_val_sem_j = stats.wilcoxon(scores_sem_j, scores_bruto, alternative="greater")
            else:
                p_val_sem_j = np.nan
        else:
            p_val_sem_j = np.nan
            
        # Guarda os p-values calculados para esta métrica nesta matéria
        registros_testes.append({
            "materia": materia,
            "metrica": metric,
            "p_val_Alt_Just_vs_Bruto": p_val_alt_just,
            "p_val_Alt_SemJust_vs_Bruto": p_val_sem_j
        })

# Consolida os resultados em DataFrame
df_p_values = pd.DataFrame(registros_testes)

# Define o nível de significância rigoroso do seu paper (Alpha = 0.05)
ALPHA_CORTE = 0.05

# Cria as colunas de veredito se houve ganho ou não em relação ao bruto
df_p_values["Melhorou_Alt_Just?"] = df_p_values["p_val_Alt_Just_vs_Bruto"].apply(
    lambda p: "SIM (*)" if p < ALPHA_CORTE else "Não"
)
df_p_values["Melhorou_Alt_SemJust?"] = df_p_values["p_val_Alt_SemJust_vs_Bruto"].apply(
    lambda p: "SIM (*)" if p < ALPHA_CORTE else "Não"
)

# Reorganiza as colunas para melhor leitura na tela
colunas_ordenadas = [
    "materia", "metrica", 
    "p_val_Alt_Just_vs_Bruto", "Melhorou_Alt_Just?",
    "p_val_Alt_SemJust_vs_Bruto", "Melhorou_Alt_SemJust?"
]
df_p_values = df_p_values[colunas_ordenadas]

print("\n>>> TABELA DE VEREDITO FINAL (Confiança de 95%) <<<")
display(df_p_values)

# Limpeza de memória final
del df_filtrado, registros_testes
gc.collect()

--- Calculando Média e Desvio Padrão por Tratamento ---

======================================================================
INICIANDO ANÁLISE ESTATÍSTICA COMPLETA
======================================================================

--- 1. Calculando Média e Desvio Padrão por Tratamento ---

                                                    ari_mean   ari_std  \
materia      tipo_texto
MPV_612_2013 texto                                  0.139324  0.054087
             texto_preprocessado                    0.180650  0.057511
             texto_preprocessado_sem_justificativa  0.138886  0.050982
PEC_6_2019   texto                                  0.251169  0.120150
             texto_preprocessado                    0.305457  0.115174
             texto_preprocessado_sem_justificativa  0.129131  0.038609
PLP_68_2024  texto                                  0.261579  0.115821
             texto_preprocessado                    0.278624  0.118419
             texto_preprocessado_sem_justificativa  0.198373  0.124567

                                                    v_measure_mean  \
materia      tipo_texto
MPV_612_2013 texto                                        0.621332
             texto_preprocessado                          0.670982
             texto_preprocessado_sem_justificativa        0.652380
PEC_6_2019   texto                                        0.591832
             texto_preprocessado                          0.655595
             texto_preprocessado_sem_justificativa        0.506716
PLP_68_2024  texto                                        0.757159
             texto_preprocessado                          0.769602
             texto_preprocessado_sem_justificativa        0.721185

                                                    v_measure_std
materia      tipo_texto
MPV_612_2013 texto                                       0.058674
             texto_preprocessado                         0.040984
             texto_preprocessado_sem_justificativa       0.042666
PEC_6_2019   texto                                       0.113172
             texto_preprocessado                         0.084901
             texto_preprocessado_sem_justificativa       0.056810
PLP_68_2024  texto                                       0.086811
             texto_preprocessado                         0.082513
             texto_preprocessado_sem_justificativa       0.097399

--- 2. Executando Testes de Wilcoxon (Melhora vs. Bruto) ---

>>> TABELA DE VEREDITO FINAL (Confiança de 95%) <<<

,materia,metrica,p_val_Alt_Just_vs_Bruto,Melhorou_Alt_Just?,p_val_Alt_SemJust_vs_Bruto,Melhorou_Alt_SemJust?
0,PEC_6_2019,ari,0.002003,SIM (*),0.999973,Não
1,PEC_6_2019,v_measure,0.000210,SIM (*),0.998833,Não
2,MPV_612_2013,ari,0.002800,SIM (*),0.633137,Não
3,MPV_612_2013,v_measure,0.000008,SIM (*),0.019245,SIM (*)
4,PLP_68_2024,ari,0.011837,SIM (*),0.997200,Não
5,PLP_68_2024,v_measure,0.001167,SIM (*),0.982883,Não

0

In [75]:
import gc
import scipy.stats as stats
import pandas as pd
import numpy as np

# ============================================================
# 0. FILTRO BASE (APENAS PLP 68)
# ============================================================
df_filtrado = df_all[
    (df_all["tipo_texto"] == "texto_preprocessado") &
    (df_all["materia"] == "PLP_68_2024")
].copy()

metricas = ["ari", "v_measure"]

# ============================================================
# 1. ESTATÍSTICAS DESCRITIVAS
# ============================================================
df_estatisticas = (
    df_filtrado
    .groupby("nivel")[metricas]
    .agg(["mean", "std"])
)

df_estatisticas.columns = [
    f"{metrica}_{estat}"
    for metrica, estat in df_estatisticas.columns
]

display(df_estatisticas)

# ============================================================
# 2. TESTE HIERÁRQUICO:
#    tema_nivel_2 > tema
#    tema_macro > tema
# ============================================================

nivel_ref = "tema"
niveles_teste = ["tema_nivel_2", "tema_macro"]

df_ref = df_filtrado[df_filtrado["nivel"] == nivel_ref]

resultados = []

for nivel in niveles_teste:

    df_comp = df_filtrado[df_filtrado["nivel"] == nivel]

    if df_comp.empty or df_ref.empty:
        continue

    for metrica in metricas:

        # ============================================================
        # 🔥 ALINHAMENTO POR EMBEDDING (CRÍTICO)
        # ============================================================
        df_join = df_ref[["embedding", metrica]].rename(columns={metrica: "tema"}).merge(
            df_comp[["embedding", metrica]].rename(columns={metrica: "comp"}),
            on="embedding",
            how="inner"
        )

        if len(df_join) < 3:
            p = np.nan
            sig = "n.s."
        else:
            # ========================================================
            # H1: nível > tema (teste DIRECIONAL correto)
            # ========================================================
            _, p = stats.wilcoxon(
                df_join["comp"],
                df_join["tema"],
                alternative="greater"
            )

            sig = "SIM (*)" if p < 0.05 else "Não"

        resultados.append({
            "materia": "PLP_68_2024",
            "comparacao": f"{nivel} vs tema",
            "metrica": metrica,
            "p_value": p,
            "melhora_hierarquica?": sig
        })

df_p_values = pd.DataFrame(resultados)

display(df_p_values)

gc.collect()

              ari_mean   ari_std  v_measure_mean  v_measure_std
nivel
tema          0.278624  0.118419        0.769602       0.082513
tema_macro    0.132720  0.059670        0.383474       0.078177
tema_nivel_2  0.264530  0.139713        0.654750       0.100346

       materia            comparacao    metrica   p_value melhora_hierarquica?
0  PLP_68_2024  tema_nivel_2 vs tema        ari  0.778851                  Não
1  PLP_68_2024  tema_nivel_2 vs tema  v_measure  1.000000                  Não
2  PLP_68_2024    tema_macro vs tema        ari  0.999989                  Não
3  PLP_68_2024    tema_macro vs tema  v_measure  1.000000                  Não

0

In [78]:
MODEL_SIZE = {
    "F2LLM_v2_14B": 14.0,
    "Octen_Embedding_8B": 8.0,
    "Qwen3_Embedding_8B": 8.0,
    "llama_embed_nemotron_8b": 8.0,
    "harrier_oss_v1_27b": 27.0,
    "KaLM_Embedding_Gemma3_12B_2511": 12.0,
    "jina_embeddings_v5_text_small": 0.6,      # 330M
    "serafim_335m_portuguese_pt_sentence_encoder": 0.335,
    "serafim_335m_portuguese_pt_sentence_encoder_ir": 0.335,
    "bertimbau_tuned": 0.335,                   # BERTimbau Large ≈335M
    "ICT_TIME_and_Querit_embedding_v1": 4  # preencher quando souber
}


def get_model_size(name):
    for model, size in MODEL_SIZE.items():
        if model in name:
            return size
    return np.nan

In [79]:
df_all["size"] = df_all.embedding.apply(get_model_size)

In [81]:
embedding_cols_abertos = [
    'embedding__codefuse_ai__F2LLM_v2_14B__texto',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado_sem_justificativa',
       'embedding__Octen__Octen_Embedding_8B__texto',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__Qwen__Qwen3_Embedding_8B__texto',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__nvidia__llama_embed_nemotron_8b__texto',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado_sem_justificativa',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado_sem_justificativa',
       'embedding__joaorobson__harrier_oss_v1_27b__texto',
       'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado',
       'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado_sem_justificativa',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado_sem_justificativa',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado_sem_justificativa',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado_sem_justificativa',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado_sem_justificativa']

df_abertos = df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel == "tema") & (df_all.embedding.isin(embedding_cols_abertos))].copy()

In [85]:
from scipy.stats import spearmanr
import pandas as pd

metrics = ["ari", "v_measure"]

results = []

for materia in df_abertos["materia"].unique():
    sub = df_abertos[df_abertos["materia"] == materia]
    
    for metric in metrics:
        rho, p = spearmanr(sub["size"], sub[metric])
        
        results.append({
            "materia": materia,
            "metric": metric,
            "spearman_rho": rho,
            "p_value": p
        })

df_corr = pd.DataFrame(results)
df_corr

        materia     metric  spearman_rho   p_value
0    PEC_6_2019        ari      0.815973  0.000372
1    PEC_6_2019  v_measure      0.841257  0.000163
2  MPV_612_2013        ari      0.836660  0.000191
3  MPV_612_2013  v_measure      0.818272  0.000347
4   PLP_68_2024        ari      0.809078  0.000457
5   PLP_68_2024  v_measure      0.832063  0.000223

In [86]:
import pandas as pd

metricas = ["ari", "v_measure"]

ranks = []

for metrica in metricas:
    r = (
        df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel == "tema")].groupby("materia")
          .apply(lambda x:
                 x.assign(
                     rank=x[metrica].rank(
                         ascending=False,
                         method="average"
                     )
                 )[["embedding", "materia", "rank"]]
          )
          .reset_index(drop=True)
    )
    r["metrica"] = metrica
    ranks.append(r)

ranks = pd.concat(ranks)

ranking_medio = (
    ranks.groupby("embedding")
         .agg(
             ranking_medio=("rank","mean"),
             desvio=("rank","std"),
             melhor=("rank","min"),
             pior=("rank","max")
         )
         .sort_values("ranking_medio")
)

ranking_medio

C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_13788\3623029288.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x:
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_13788\3623029288.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x:

,ranking_medio,desvio,melhor,pior
embedding,,,,
embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado,2.333333,0.816497,1.0,3.0
embedding__Octen__Octen_Embedding_8B__texto_preprocessado,3.000000,1.549193,1.0,4.0
embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado,3.666667,3.076795,1.0,8.0
embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado,3.666667,1.751190,1.0,5.0
embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado,6.166667,3.868678,2.0,11.0
embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado,6.833333,1.602082,6.0,10.0
embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado,7.333333,0.816497,6.0,8.0
bm25l_preprocess__texto_preprocessado,7.500000,4.086563,3.0,13.0
embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado,8.166667,3.371449,3.0,11.0
embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado,9.166667,3.125167,6.0,14.0
bm25l_raw__texto_preprocessado,10.500000,2.073644,9.0,14.0
embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado,12.500000,2.073644,10.0,15.0
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado,13.166667,0.752773,12.0,14.0
embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado,14.166667,2.401388,11.0,17.0
embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado,14.500000,3.987480,9.0,18.0
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado,15.000000,1.673320,12.0,17.0
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado,16.333333,0.816497,15.0,17.0
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado,17.000000,1.673320,14.0,18.0

In [77]:
df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel=="tema") & (
    (~df_all.embedding.str.contains("PORTULAN")) & (~df_all.embedding.str.contains("jose")))].describe()

             ari  v_measure
count  36.000000  36.000000
mean    0.306684   0.734933
std     0.092990   0.071535
min     0.122336   0.568779
25%     0.237072   0.692343
50%     0.318110   0.716022
75%     0.361091   0.808270
max     0.528830   0.832587

In [70]:
with pd.option_context('display.max_columns', None,
                       'display.max_colwidth', None,
                       'display.max_rows', None):
    display(
        df_clustering[(df_clustering.nivel == "tema") & (df_clustering.tipo_texto == "texto_preprocessado") 
            & (df_clustering.materia == "MPV_612_2013")
            ].sort_values(["materia", "nome_latex", "v_measure"]
                                                                                    )[["embedding",	"nome_latex",	"ari",
                                                                                        "v_measure",	"materia"]]
    )

,embedding,nome_latex,ari,v_measure,materia
93,embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado,BERT (mp),0.113411,0.608858,MPV_612_2013
98,embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado,BERT (trunc),0.097615,0.603205,MPV_612_2013
68,bm25l_raw__texto_preprocessado,BM25L,0.185694,0.688855,MPV_612_2013
61,bm25l_preprocess__texto_preprocessado,BM25L (prep),0.224040,0.711967,MPV_612_2013
64,embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado,F2LLM,0.208311,0.690072,MPV_612_2013
71,embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado,GOOGLE,0.174140,0.653325,MPV_612_2013
54,embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado,HARRIER,0.277524,0.714753,MPV_612_2013
55,embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado,ICTT,0.255449,0.719338,MPV_612_2013
88,embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado,JINA (text-m),0.122336,0.652814,MPV_612_2013
56,embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado,KALM,0.254482,0.708883,MPV_612_2013
66,embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado,NEMO,0.201859,0.703833,MPV_612_2013
57,embedding__Octen__Octen_Embedding_8B__texto_preprocessado,OCTEN,0.241417,0.710784,MPV_612_2013
62,embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado,OPENAI,0.220633,0.707353,MPV_612_2013
73,embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado,QWEN3,0.171193,0.687444,MPV_612_2013
85,embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado,SRFB (mp),0.141892,0.628142,MPV_612_2013
92,embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado,SRFB (trunc),0.114029,0.628669,MPV_612_2013
87,embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado,SRFIR (mp),0.128265,0.637146,MPV_612_2013
89,embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado,SRFIR (trunc),0.119409,0.622227,MPV_612_2013

In [99]:
(
    df_clustering[df_clustering.nivel == "tema"]
    .groupby(["modelo", "tipo_texto"])[["ari", "v_measure"]]
    .mean()
    .sort_values(by=["tipo_texto", "v_measure"], ascending=[True, False])
)

                                                          ari  v_measure
modelo        tipo_texto
kmeans        texto                                  0.206910   0.677740
agglomerative texto                                  0.214428   0.655818
kmeans        texto_preprocessado                    0.245362   0.712078
agglomerative texto_preprocessado                    0.245007   0.691306
kmeans        texto_preprocessado_sem_justificativa  0.187736   0.670498
agglomerative texto_preprocessado_sem_justificativa  0.152101   0.622666

In [78]:
# Defina exatamente qual subconjunto você quer analisar para evitar overlap
SCENARIO_TEXT = "texto_preprocessado"  # ou "texto", "texto_preprocessado_sem_justificativa"
SCENARIO_LEVEL = "tema"                # ou "tema_macro", "tema_nivel_2"

# 1. Filtro Cirúrgico
df_fatiado = df_clustering[
    (df_clustering["tipo_texto"] == SCENARIO_TEXT) &
    (df_clustering["nivel"] == SCENARIO_LEVEL)
].copy()

# 2. Pivoteamento Seguro (Agora cada par matéria/embedding tem apenas UMA linha)
df_artigo = df_fatiado.pivot_table(
    index=["materia", "embedding"],
    columns=["modelo"],
    values=["ari", "v_measure"],
    aggfunc="first" # Totalmente seguro aqui, pois removemos as dimensões ocultas
)

# 3. Formatação idêntica ao LaTeX para validação visual rápida
df_artigo = df_artigo.reorder_levels(["modelo", None], axis=1).sort_index(axis=1, ascending=[False, True])
df_artigo = df_artigo.sort_values(by=["materia", ("kmeans", "ari")], ascending=[True, False])

display(df_artigo)

,nivel,embedding,modelo,ari,v_measure,materia,tipo_texto
0,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,kmeans,0.574067,0.792848,PEC_6_2019,texto_preprocessado
1,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,kmeans,0.561325,0.811357,PEC_6_2019,texto_preprocessado
2,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,kmeans,0.538841,0.801856,PEC_6_2019,texto_preprocessado
3,tema,embedding__jinaai__jina_embeddings_v5_text_sma...,kmeans,0.531151,0.774892,PEC_6_2019,texto_preprocessado
4,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,agglomerative,0.528830,0.786561,PEC_6_2019,texto_preprocessado
...,...,...,...,...,...,...,...
535,tema,embedding__PORTULAN__serafim_335m_portuguese_p...,agglomerative,0.019804,0.543635,PLP_68_2024,texto
536,tema_nivel_2,embedding__PORTULAN__serafim_335m_portuguese_p...,agglomerative,0.018159,0.374672,PLP_68_2024,texto
537,tema_macro,bm25l_preprocess__texto_preprocessado,kmeans,0.017812,0.331468,PLP_68_2024,texto_preprocessado
538,tema_macro,bm25l_raw__texto,kmeans,0.016930,0.320156,PLP_68_2024,texto
539,tema_macro,embedding__Octen__Octen_Embedding_8B__texto_pr...,agglomerative,0.004350,0.250027,PLP_68_2024,texto_preprocessado_sem_justificativa

In [73]:
(
    df_clustering[
        (df_clustering.tipo_texto == "texto_preprocessado") &
        (df_clustering.nivel == "tema") &
        (df_clustering.materia == "MPV_612_2013")
    ]
    .groupby(["modelo", "embedding"])[["ari", "v_measure"]]
    .first() # Garante o primeiro registro real encontrado
)

                                                                       ari  \
modelo        embedding
agglomerative bm25l_preprocess__texto_preprocessado               0.224040
              bm25l_raw__texto_preprocessado                      0.185694
              embedding__Octen__Octen_Embedding_8B__texto_pre...  0.241417
              embedding__PORTULAN__serafim_335m_portuguese_pt...  0.141892
              embedding__PORTULAN__serafim_335m_portuguese_pt...  0.114029
              embedding__PORTULAN__serafim_335m_portuguese_pt...  0.128265
              embedding__PORTULAN__serafim_335m_portuguese_pt...  0.119409
              embedding__Qwen__Qwen3_Embedding_8B__texto_prep...  0.171193
              embedding__codefuse_ai__F2LLM_v2_14B__texto_pre...  0.208311
              embedding__google__gemini_embedding_2__trunc819...  0.174140
              embedding__jinaai__jina_embeddings_v5_text_smal...  0.096137
              embedding__jinaai__jina_embeddings_v5_text_smal...  0.122336
              embedding__joaorobson__KaLM_Embedding_Gemma3_12...  0.254482
              embedding__joaorobson__harrier_oss_v1_27b__text...  0.277524
              embedding__josedossantos__bertimbau_tuned__mean...  0.113411
              embedding__josedossantos__bertimbau_tuned__trun...  0.097615
              embedding__nvidia__llama_embed_nemotron_8b__tex...  0.201859
              embedding__openai__text_embedding_3_large__trun...  0.220633
kmeans        bm25l_preprocess__texto_preprocessado               0.119621
              bm25l_raw__texto_preprocessado                      0.126916
              embedding__Octen__Octen_Embedding_8B__texto_pre...  0.102078
              embedding__PORTULAN__serafim_335m_portuguese_pt...  0.093711
              embedding__PORTULAN__serafim_335m_portuguese_pt...  0.106540
              embedding__PORTULAN__serafim_335m_portuguese_pt...  0.083193
              embedding__PORTULAN__serafim_335m_portuguese_pt...  0.078316
              embedding__Qwen__Qwen3_Embedding_8B__texto_prep...  0.110781
              embedding__codefuse_ai__F2LLM_v2_14B__texto_pre...  0.090192
              embedding__google__gemini_embedding_2__trunc819...  0.093760
              embedding__jinaai__jina_embeddings_v5_text_smal...  0.076315
              embedding__jinaai__jina_embeddings_v5_text_smal...  0.092001
              embedding__joaorobson__KaLM_Embedding_Gemma3_12...  0.113982
              embedding__joaorobson__harrier_oss_v1_27b__text...  0.106906
              embedding__josedossantos__bertimbau_tuned__mean...  0.060677
              embedding__josedossantos__bertimbau_tuned__trun...  0.068145
              embedding__nvidia__llama_embed_nemotron_8b__tex...  0.102479
              embedding__openai__text_embedding_3_large__trun...  0.097621

                                                                  v_measure
modelo        embedding
agglomerative bm25l_preprocess__texto_preprocessado                0.711967
              bm25l_raw__texto_preprocessado                       0.688855
              embedding__Octen__Octen_Embedding_8B__texto_pre...   0.710784
              embedding__PORTULAN__serafim_335m_portuguese_pt...   0.628142
              embedding__PORTULAN__serafim_335m_portuguese_pt...   0.628669
              embedding__PORTULAN__serafim_335m_portuguese_pt...   0.637146
              embedding__PORTULAN__serafim_335m_portuguese_pt...   0.622227
              embedding__Qwen__Qwen3_Embedding_8B__texto_prep...   0.687444
              embedding__codefuse_ai__F2LLM_v2_14B__texto_pre...   0.690072
              embedding__google__gemini_embedding_2__trunc819...   0.653325
              embedding__jinaai__jina_embeddings_v5_text_smal...   0.600271
              embedding__jinaai__jina_embeddings_v5_text_smal...   0.652814
              embedding__joaorobson__KaLM_Embedding_Gemma3_12...   0.708883
              embedding__joaorobson__harrier_oss_v1_27b__text...   0.714753
              embedding__josedossantos__bertimbau_tuned__mean...   0.608858
              embedding__josedossantos__bertimbau_tuned__trun...   0.603205
              embedding__nvidia__llama_embed_nemotron_8b__tex...   0.703833
              embedding__openai__text_embedding_3_large__trun...   0.707353
kmeans        bm25l_preprocess__texto_preprocessado                0.667790
              bm25l_raw__texto_preprocessado                       0.674273
              embedding__Octen__Octen_Embedding_8B__texto_pre...   0.679327
              embedding__PORTULAN__serafim_335m_portuguese_pt...   0.637155
              embedding__PORTULAN__serafim_335m_portuguese_pt...   0.662836
              embedding__PORTULAN__serafim_335m_portuguese_pt...   0.642324
              embedding__PORTULAN__serafim_335m_portuguese_pt...   0.631438
              embedding__Qwen__Qwen3_Embedding_8B__texto_prep...   0.672787
              embedding__codefuse_ai__F2LLM_v2_14B__texto_pre...   0.660990
              embedding__google__gemini_embedding_2__trunc819...   0.671056
              embedding__jinaai__jina_embeddings_v5_text_smal...   0.628174
              embedding__jinaai__jina_embeddings_v5_text_smal...   0.656127
              embedding__joaorobson__KaLM_Embedding_Gemma3_12...   0.683650
              embedding__joaorobson__harrier_oss_v1_27b__text...   0.675392
              embedding__josedossantos__bertimbau_tuned__mean...   0.607599
              embedding__josedossantos__bertimbau_tuned__trun...   0.610504
              embedding__nvidia__llama_embed_nemotron_8b__tex...   0.670505
              embedding__openai__text_embedding_3_large__trun...   0.673785

In [54]:
df_clustering[
    (df_clustering.tipo_texto == "texto_preprocessado") &
    (df_clustering.nivel == "tema")
].groupby("embedding")[["ari", "v_measure"]].mean().sort_values("v_measure", ascending=False)

                                                         ari  v_measure
embedding
embedding__codefuse_ai__F2LLM_v2_14B__texto_pre...  0.354546   0.769602
embedding__Octen__Octen_Embedding_8B__texto_pre...  0.340458   0.768330
embedding__joaorobson__harrier_oss_v1_27b__text...  0.356869   0.767064
embedding__Qwen__Qwen3_Embedding_8B__texto_prep...  0.328083   0.763192
embedding__openai__text_embedding_3_large__trun...  0.296440   0.743630
embedding__nvidia__llama_embed_nemotron_8b__tex...  0.295039   0.740153
embedding__jinaai__jina_embeddings_v5_text_smal...  0.295010   0.736394
embedding__joaorobson__KaLM_Embedding_Gemma3_12...  0.272481   0.727974
bm25l_raw__texto_preprocessado                      0.219744   0.693793
bm25l_preprocess__texto_preprocessado               0.213187   0.692188
embedding__PORTULAN__serafim_335m_portuguese_pt...  0.198170   0.684079
embedding__google__gemini_embedding_2__trunc819...  0.209939   0.680823
embedding__josedossantos__bertimbau_tuned__mean...  0.201355   0.665952
embedding__josedossantos__bertimbau_tuned__trun...  0.206185   0.660550
embedding__PORTULAN__serafim_335m_portuguese_pt...  0.182544   0.658188
embedding__jinaai__jina_embeddings_v5_text_smal...  0.177562   0.647548
embedding__PORTULAN__serafim_335m_portuguese_pt...  0.129098   0.615913
embedding__PORTULAN__serafim_335m_portuguese_pt...  0.136610   0.615088

In [32]:
df_clustering[df_clustering.embedding.str.startswith("bm25")]

,nivel,embedding,modelo,ari,v_measure,materia,tipo_texto
33,tema,bm25l_raw__texto_preprocessado,kmeans,0.253143,0.620874,PEC_6_2019,texto_preprocessado
34,tema,bm25l_preprocess__texto_preprocessado_sem_just...,kmeans,0.240091,0.611833,PEC_6_2019,texto_preprocessado_sem_justificativa
37,tema,bm25l_raw__texto_preprocessado_sem_justificativa,kmeans,0.225074,0.595605,PEC_6_2019,texto_preprocessado_sem_justificativa
41,tema,bm25l_raw__texto,kmeans,0.196836,0.567936,PEC_6_2019,texto
42,tema,bm25l_preprocess__texto_preprocessado,kmeans,0.191917,0.590701,PEC_6_2019,texto_preprocessado
43,tema,bm25l_preprocess__texto,kmeans,0.186190,0.554209,PEC_6_2019,texto
55,tema,bm25l_raw__texto_preprocessado,kmeans,0.126916,0.674273,MPV_612_2013,texto_preprocessado
56,tema,bm25l_preprocess__texto_preprocessado,kmeans,0.119621,0.667790,MPV_612_2013,texto_preprocessado
65,tema,bm25l_preprocess__texto_preprocessado_sem_just...,kmeans,0.106110,0.662728,MPV_612_2013,texto_preprocessado_sem_justificativa
86,tema,bm25l_raw__texto_preprocessado_sem_justificativa,kmeans,0.084988,0.638426,MPV_612_2013,texto_preprocessado_sem_justificativa
90,tema,bm25l_preprocess__texto,kmeans,0.078954,0.642843,MPV_612_2013,texto
94,tema,bm25l_raw__texto,kmeans,0.076090,0.620911,MPV_612_2013,texto
175,tema,bm25l_preprocess__texto_preprocessado_sem_just...,kmeans,0.205480,0.798084,PLP_68_2024,texto_preprocessado_sem_justificativa
182,tema,bm25l_raw__texto_preprocessado_sem_justificativa,kmeans,0.193301,0.786944,PLP_68_2024,texto_preprocessado_sem_justificativa
203,tema,bm25l_raw__texto,kmeans,0.147305,0.767506,PLP_68_2024,texto
209,tema,bm25l_raw__texto_preprocessado,kmeans,0.138598,0.766974,PLP_68_2024,texto_preprocessado
217,tema_nivel_2,bm25l_raw__texto_preprocessado_sem_justificativa,kmeans,0.131686,0.629426,PLP_68_2024,texto_preprocessado_sem_justificativa
219,tema_nivel_2,bm25l_preprocess__texto_preprocessado_sem_just...,kmeans,0.130104,0.672311,PLP_68_2024,texto_preprocessado_sem_justificativa
222,tema_nivel_2,bm25l_raw__texto,kmeans,0.127111,0.628938,PLP_68_2024,texto
228,tema,bm25l_preprocess__texto_preprocessado,kmeans,0.110281,0.760228,PLP_68_2024,texto_preprocessado
239,tema,bm25l_preprocess__texto,kmeans,0.101373,0.748661,PLP_68_2024,texto
243,tema_nivel_2,bm25l_raw__texto_preprocessado,kmeans,0.091480,0.632563,PLP_68_2024,texto_preprocessado
252,tema_nivel_2,bm25l_preprocess__texto,kmeans,0.068575,0.593531,PLP_68_2024,texto
255,tema_macro,bm25l_preprocess__texto_preprocessado_sem_just...,kmeans,0.066239,0.401352,PLP_68_2024,texto_preprocessado_sem_justificativa
260,tema_nivel_2,bm25l_preprocess__texto_preprocessado,kmeans,0.061302,0.603368,PLP_68_2024,texto_preprocessado
261,tema_macro,bm25l_preprocess__texto,kmeans,0.056295,0.356682,PLP_68_2024,texto
263,tema_macro,bm25l_raw__texto_preprocessado,kmeans,0.048897,0.349186,PLP_68_2024,texto_preprocessado
266,tema_macro,bm25l_raw__texto_preprocessado_sem_justificativa,kmeans,0.042744,0.341991,PLP_68_2024,texto_preprocessado_sem_justificativa
268,tema_macro,bm25l_raw__texto,kmeans,0.018469,0.320002,PLP_68_2024,texto
269,tema_macro,bm25l_preprocess__texto_preprocessado,kmeans,0.017046,0.331510,PLP_68_2024,texto_preprocessado

In [58]:
resultados_df.to_parquet("../data/datasets/resultados_clustering.parquet", index=False)

In [63]:
from IPython.display import display

TOP_K = 5

metricas_ordem = ["ari", "ami", "nmi", "v_measure"]

def exibir_bloco(df_base, titulo_extra):

    for materia in sorted(df_base["materia"].unique()):

        df_m = df_base[df_base["materia"] == materia]

        for nivel in sorted(df_m["nivel"].unique()):

            df_n = df_m[df_m["nivel"] == nivel]

            for tipo_texto in sorted(df_n["tipo_texto"].unique()):

                df_t = df_n[df_n["tipo_texto"] == tipo_texto]

                print("\n" + "=" * 120)
                print(f"{titulo_extra}")
                print(f"MATERIA: {materia} | NIVEL: {nivel} | TIPO: {tipo_texto}")
                print("=" * 120)

                df_t = df_t.copy()
                df_t["score_geral"] = df_t[metricas_ordem].mean(axis=1)

                df_view = (
                    df_t.sort_values(
                        ["algoritmo", "score_geral"],
                        ascending=[True, False]
                    )
                    .groupby("algoritmo", group_keys=False)
                    .head(TOP_K)
                    [
                        [
                            "algoritmo",
                            "embedding_space",
                            "use_umap",
                            "embedding",
                            "ari",
                            "ami",
                            "nmi",
                            "v_measure",
                            "homogeneity",
                            "completeness",
                            "n_clusters_pred",
                            "score_geral",
                        ]
                    ]
                    .reset_index(drop=True)
                )

                display(df_view)

In [64]:
df_raw = resultados_df[resultados_df["use_umap"] == False]
df_umap = resultados_df[resultados_df["use_umap"] == True]

print("\n\n############################")
print("### RESULTADOS SEM UMAP ###")
print("############################")
exibir_bloco(df_raw, "RAW EMBEDDINGS")

print("\n\n###########################")
print("### RESULTADOS COM UMAP ###")
print("###########################")
exibir_bloco(df_umap, "UMAP EMBEDDINGS")

############################
### RESULTADOS SEM UMAP ###
############################

========================================================================================================================
RAW EMBEDDINGS
MATERIA: MPV_612_2013 | NIVEL: tema | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__openai__text_embedding_3_large__tru...,0.234123,0.479370,0.721221,0.721221,0.791095,0.662689,58,0.538984
1,agglomerative,raw,False,embedding__openai__text_embedding_3_large__mea...,0.234123,0.479370,0.721221,0.721221,0.791095,0.662689,58,0.538984
2,agglomerative,raw,False,embedding__google__gemini_embedding_2__trunc81...,0.229528,0.439556,0.695871,0.695871,0.751533,0.647885,58,0.515207
3,agglomerative,raw,False,embedding__google__gemini_embedding_2__meanpoo...,0.229528,0.439556,0.695871,0.695871,0.751533,0.647885,58,0.515207
4,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.182111,0.407899,0.686624,0.686624,0.761745,0.624990,58,0.490815
5,kmeans,raw,False,embedding__jinaai__jina_embeddings_v5_text_sma...,0.135912,0.368098,0.672608,0.672608,0.766225,0.599376,58,0.462306
6,kmeans,raw,False,embedding__openai__text_embedding_3_large__tru...,0.118744,0.368478,0.679079,0.679079,0.790632,0.595112,58,0.461345
7,kmeans,raw,False,embedding__openai__text_embedding_3_large__mea...,0.118744,0.365237,0.678186,0.678186,0.790524,0.593803,58,0.460088
8,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.112637,0.368283,0.677395,0.677395,0.783937,0.596347,58,0.458928
9,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.092528,0.347797,0.663943,0.663943,0.756450,0.591596,58,0.442053

========================================================================================================================
RAW EMBEDDINGS
MATERIA: MPV_612_2013 | NIVEL: tema | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.191741,0.431659,0.699121,0.699121,0.777966,0.634787,58,0.505411
1,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.236870,0.411063,0.683678,0.683678,0.747413,0.629959,58,0.503823
2,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.205328,0.419538,0.691960,0.691960,0.767098,0.630228,58,0.502197
3,agglomerative,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.172873,0.410387,0.691535,0.691535,0.778510,0.622042,58,0.491583
4,agglomerative,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.214929,0.382130,0.663390,0.663390,0.711116,0.621667,58,0.480960
5,kmeans,raw,False,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.133623,0.377639,0.679031,0.679031,0.773090,0.605377,58,0.467331
6,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.110874,0.382007,0.683099,0.683099,0.784484,0.604920,58,0.464770
7,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.106541,0.376186,0.680839,0.680839,0.780891,0.603513,58,0.461101
8,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.111869,0.373290,0.679440,0.679440,0.780352,0.601638,58,0.461010
9,kmeans,raw,False,embedding__openai__text_embedding_3_large__mea...,0.098983,0.324823,0.653210,0.653210,0.752075,0.577318,58,0.432557

========================================================================================================================
RAW EMBEDDINGS
MATERIA: MPV_612_2013 | NIVEL: tema | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.277524,0.463818,0.714753,0.714753,0.788896,0.653349,58,0.542712
1,agglomerative,raw,False,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.254482,0.454094,0.708883,0.708883,0.782033,0.648247,58,0.531585
2,agglomerative,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.241417,0.450808,0.710784,0.710784,0.794070,0.643310,58,0.528448
3,agglomerative,raw,False,embedding__openai__text_embedding_3_large__tru...,0.220633,0.445598,0.707353,0.707353,0.788441,0.641389,58,0.520234
4,agglomerative,raw,False,embedding__nvidia__llama_embed_nemotron_8b__te...,0.201859,0.447192,0.703833,0.703833,0.774366,0.645077,58,0.514180
5,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.129516,0.407703,0.696096,0.696096,0.798151,0.617181,58,0.482353
6,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.114129,0.398541,0.693085,0.693085,0.798724,0.612125,58,0.474710
7,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.113847,0.386778,0.687335,0.687335,0.792257,0.606953,58,0.468824
8,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.122157,0.373634,0.677043,0.677043,0.773160,0.602181,58,0.462469
9,kmeans,raw,False,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.107822,0.366841,0.674642,0.674642,0.772394,0.598853,58,0.455987

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PEC_6_2019 | NIVEL: tema | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.196153,0.449764,0.599494,0.599494,0.542485,0.669891,29,0.461226
1,agglomerative,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.190014,0.441672,0.588188,0.588188,0.526091,0.666907,29,0.452016
2,agglomerative,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.164449,0.413204,0.567194,0.567194,0.500412,0.654545,29,0.428010
3,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.162133,0.414624,0.564374,0.564374,0.492429,0.660938,29,0.426376
4,agglomerative,raw,False,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.164238,0.410610,0.562198,0.562198,0.494483,0.651401,29,0.424811
5,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.375460,0.552875,0.698204,0.698204,0.710934,0.685922,29,0.581186
6,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.323802,0.503960,0.668525,0.668525,0.687350,0.650705,29,0.541203
7,kmeans,raw,False,embedding__openai__text_embedding_3_large__tru...,0.316487,0.488415,0.655801,0.655801,0.668499,0.643576,29,0.529126
8,kmeans,raw,False,embedding__openai__text_embedding_3_large__mea...,0.316487,0.488415,0.655801,0.655801,0.668499,0.643576,29,0.529126
9,kmeans,raw,False,embedding__jinaai__jina_embeddings_v5_text_sma...,0.296963,0.459274,0.639131,0.639131,0.656426,0.622724,29,0.508625

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PEC_6_2019 | NIVEL: tema | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.502200,0.701646,0.786200,0.786200,0.747550,0.829064,29,0.694061
1,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.440935,0.677735,0.767465,0.767465,0.716543,0.826179,29,0.663400
2,agglomerative,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.433797,0.682505,0.768525,0.768525,0.708807,0.839230,29,0.663338
3,agglomerative,raw,False,embedding__jinaai__jina_embeddings_v5_text_sma...,0.365572,0.600048,0.707838,0.707838,0.652581,0.773319,29,0.595324
4,agglomerative,raw,False,embedding__PORTULAN__serafim_900m_portuguese_p...,0.291306,0.474189,0.622662,0.622662,0.592610,0.655925,29,0.502705
5,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.520124,0.686717,0.790473,0.790473,0.811803,0.770236,29,0.696947
6,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.487110,0.674936,0.782727,0.782727,0.802871,0.763569,29,0.681875
7,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.459825,0.646769,0.763231,0.763231,0.782706,0.744703,29,0.658264
8,kmeans,raw,False,embedding__jinaai__jina_embeddings_v5_text_sma...,0.416877,0.584447,0.720636,0.720636,0.733216,0.708480,29,0.610649
9,kmeans,raw,False,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.346406,0.534288,0.685963,0.685963,0.698619,0.673758,29,0.563155

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PEC_6_2019 | NIVEL: tema | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.528830,0.703939,0.786561,0.786561,0.745024,0.833004,29,0.701473
1,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.466991,0.694486,0.780961,0.780961,0.735409,0.832530,29,0.680850
2,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.452424,0.662408,0.756060,0.756060,0.708284,0.810748,29,0.656738
3,agglomerative,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.416230,0.656443,0.748648,0.748648,0.688803,0.819883,29,0.642492
4,agglomerative,raw,False,embedding__openai__text_embedding_3_large__tru...,0.348803,0.602389,0.707559,0.707559,0.645773,0.782418,29,0.591577
5,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.524887,0.677833,0.784401,0.784401,0.806426,0.763548,29,0.692881
6,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.508715,0.669485,0.778814,0.778814,0.797863,0.760654,29,0.683957
7,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.498687,0.673579,0.779385,0.779385,0.793081,0.766154,29,0.682759
8,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.478566,0.655502,0.768599,0.768599,0.786460,0.751530,29,0.667816
9,kmeans,raw,False,embedding__openai__text_embedding_3_large__mea...,0.451098,0.617180,0.744304,0.744304,0.765701,0.724071,29,0.639222

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__google__gemini_embedding_2__trunc81...,0.320710,0.609235,0.800776,0.800776,0.810174,0.791593,261,0.632874
1,agglomerative,raw,False,embedding__google__gemini_embedding_2__meanpoo...,0.320710,0.609235,0.800776,0.800776,0.810174,0.791593,261,0.632874
2,agglomerative,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.311893,0.610628,0.800201,0.800201,0.807454,0.793078,261,0.630731
3,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.302998,0.605499,0.797914,0.797914,0.805450,0.790518,261,0.626081
4,agglomerative,raw,False,embedding__openai__text_embedding_3_large__mea...,0.288130,0.593481,0.789733,0.789733,0.793528,0.785974,261,0.615269
5,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.313709,0.603595,0.816494,0.816494,0.860946,0.776406,261,0.637573
6,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.309249,0.593625,0.811796,0.811796,0.855899,0.772015,261,0.631616
7,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.298692,0.584766,0.808002,0.808002,0.852300,0.768082,261,0.624866
8,kmeans,raw,False,embedding__openai__text_embedding_3_large__mea...,0.302102,0.580122,0.805511,0.805511,0.849192,0.766105,261,0.623312
9,kmeans,raw,False,embedding__openai__text_embedding_3_large__tru...,0.296010,0.573433,0.803099,0.803099,0.847799,0.762877,261,0.618910

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.395666,0.671849,0.831479,0.831479,0.839530,0.823580,261,0.682618
1,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.387976,0.662369,0.829588,0.829588,0.844363,0.815321,261,0.677380
2,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.365512,0.654148,0.822778,0.822778,0.831505,0.814233,261,0.666304
3,agglomerative,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.354886,0.637669,0.816636,0.816636,0.829739,0.803940,261,0.656456
4,agglomerative,raw,False,embedding__nvidia__llama_embed_nemotron_8b__texto,0.348828,0.629916,0.812097,0.812097,0.823898,0.800629,261,0.650734
5,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.349338,0.638423,0.832819,0.832819,0.878562,0.791603,261,0.663350
6,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.347917,0.639990,0.832547,0.832547,0.876345,0.792919,261,0.663250
7,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.335374,0.636121,0.831678,0.831678,0.877262,0.790597,261,0.658713
8,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.326527,0.611309,0.819531,0.819531,0.863218,0.780054,261,0.644225
9,kmeans,raw,False,embedding__jinaai__jina_embeddings_v5_text_sma...,0.300672,0.595557,0.810889,0.810889,0.851708,0.773803,261,0.629502

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.395632,0.674356,0.832587,0.832587,0.840310,0.825006,261,0.683791
1,agglomerative,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.376096,0.661836,0.827747,0.827747,0.838360,0.817399,261,0.673357
2,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.379683,0.659361,0.826861,0.826861,0.838950,0.815117,261,0.673192
3,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.356232,0.649437,0.819740,0.819740,0.826677,0.812918,261,0.661287
4,agglomerative,raw,False,embedding__openai__text_embedding_3_large__mea...,0.348799,0.644058,0.819405,0.819405,0.831197,0.807944,261,0.657917
5,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.354547,0.648936,0.836433,0.836433,0.879809,0.797133,261,0.669087
6,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.350612,0.646334,0.836467,0.836467,0.882484,0.795012,261,0.667470
7,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.348550,0.647400,0.836776,0.836776,0.882399,0.795638,261,0.667375
8,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.344323,0.636921,0.830868,0.830868,0.874018,0.791778,261,0.660745
9,kmeans,raw,False,embedding__jinaai__jina_embeddings_v5_text_sma...,0.324653,0.621183,0.824187,0.824187,0.868187,0.784431,261,0.648553

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_macro | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__openai__text_embedding_3_large__tru...,0.167604,0.378185,0.419602,0.419602,0.414239,0.425106,35,0.346248
1,agglomerative,raw,False,embedding__openai__text_embedding_3_large__mea...,0.176851,0.375139,0.416143,0.416143,0.411704,0.420680,35,0.346069
2,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.161064,0.368111,0.406001,0.406001,0.405635,0.406368,35,0.335294
3,agglomerative,raw,False,embedding__PORTULAN__serafim_900m_portuguese_p...,0.101088,0.313429,0.357782,0.357782,0.348604,0.367456,35,0.282520
4,agglomerative,raw,False,embedding__google__gemini_embedding_2__trunc81...,0.118141,0.304893,0.347997,0.347997,0.319786,0.381666,35,0.279757
5,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.128659,0.399440,0.444093,0.444093,0.537429,0.378379,35,0.354071
6,kmeans,raw,False,embedding__openai__text_embedding_3_large__tru...,0.123259,0.396216,0.440995,0.440995,0.530576,0.377293,35,0.350366
7,kmeans,raw,False,embedding__openai__text_embedding_3_large__mea...,0.127359,0.389078,0.434006,0.434006,0.521464,0.371670,35,0.346112
8,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.120842,0.389419,0.434809,0.434809,0.527141,0.370001,35,0.344969
9,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.125578,0.383415,0.429293,0.429293,0.518258,0.366397,35,0.341895

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_macro | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.233844,0.471748,0.503633,0.503633,0.532606,0.477650,35,0.428214
1,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.198421,0.434317,0.468729,0.468729,0.471904,0.465596,35,0.392549
2,agglomerative,raw,False,embedding__openai__text_embedding_3_large__mea...,0.176431,0.403976,0.442192,0.442192,0.437108,0.447396,35,0.366198
3,agglomerative,raw,False,embedding__openai__text_embedding_3_large__tru...,0.179728,0.384652,0.424478,0.424478,0.427736,0.421270,35,0.353334
4,agglomerative,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.170561,0.388985,0.425247,0.425247,0.417203,0.433607,35,0.352510
5,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.196436,0.516752,0.552255,0.552255,0.661133,0.474167,35,0.454425
6,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.150316,0.469909,0.509244,0.509244,0.614712,0.434666,35,0.409678
7,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.153977,0.462110,0.501805,0.501805,0.604501,0.428935,35,0.404924
8,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.142472,0.434365,0.476484,0.476484,0.577465,0.405564,35,0.382451
9,kmeans,raw,False,embedding__nvidia__llama_embed_nemotron_8b__texto,0.128799,0.434565,0.476248,0.476248,0.563808,0.412229,35,0.378965

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_macro | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.222725,0.449242,0.484277,0.484277,0.502619,0.467228,35,0.410130
1,agglomerative,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.202102,0.438923,0.472204,0.472204,0.470186,0.474239,35,0.396358
2,agglomerative,raw,False,embedding__jinaai__jina_embeddings_v5_text_sma...,0.197936,0.410074,0.445003,0.445003,0.445466,0.444540,35,0.374504
3,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.183720,0.411057,0.446751,0.446751,0.455172,0.438636,35,0.372070
4,agglomerative,raw,False,embedding__openai__text_embedding_3_large__mea...,0.127623,0.387900,0.424807,0.424807,0.404668,0.447056,35,0.341284
5,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.183681,0.503402,0.540161,0.540161,0.652821,0.460663,35,0.441851
6,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.158921,0.473858,0.512748,0.512748,0.614660,0.439824,35,0.414569
7,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.143264,0.472702,0.511734,0.511734,0.615664,0.437825,35,0.409859
8,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.146755,0.452778,0.492976,0.492976,0.585466,0.425721,35,0.396371
9,kmeans,raw,False,embedding__openai__text_embedding_3_large__mea...,0.139508,0.449743,0.490499,0.490499,0.588251,0.420605,35,0.392562

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_nivel_2 | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.341108,0.607186,0.700847,0.700847,0.702927,0.698779,102,0.587497
1,agglomerative,raw,False,embedding__google__gemini_embedding_2__trunc81...,0.232733,0.554180,0.658952,0.658952,0.643342,0.675339,102,0.526204
2,agglomerative,raw,False,embedding__google__gemini_embedding_2__meanpoo...,0.232733,0.554180,0.658952,0.658952,0.643342,0.675339,102,0.526204
3,agglomerative,raw,False,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.253864,0.546343,0.648920,0.648920,0.632715,0.665977,102,0.524512
4,agglomerative,raw,False,embedding__jinaai__jina_embeddings_v5_text_sma...,0.254265,0.535993,0.640597,0.640597,0.623154,0.659046,102,0.517863
5,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.293631,0.582068,0.699692,0.699692,0.745806,0.658949,102,0.568771
6,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.279069,0.576634,0.697220,0.697220,0.746446,0.654085,102,0.562536
7,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.267453,0.571397,0.693270,0.693270,0.741496,0.650934,102,0.556347
8,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.272832,0.566850,0.690377,0.690377,0.739818,0.647130,102,0.555109
9,kmeans,raw,False,embedding__openai__text_embedding_3_large__tru...,0.270835,0.561029,0.685560,0.685560,0.733405,0.643576,102,0.550746

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_nivel_2 | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.441133,0.678539,0.755717,0.755717,0.763484,0.748107,102,0.657777
1,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.389375,0.652028,0.732752,0.732752,0.731058,0.734454,102,0.626727
2,agglomerative,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.362413,0.641345,0.722866,0.722866,0.710724,0.735430,102,0.612372
3,agglomerative,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.359896,0.630991,0.717919,0.717919,0.712105,0.723828,102,0.606681
4,agglomerative,raw,False,embedding__openai__text_embedding_3_large__tru...,0.340385,0.597159,0.695192,0.695192,0.703751,0.686838,102,0.581982
5,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__texto,0.342626,0.650686,0.749150,0.749150,0.799228,0.704978,102,0.622903
6,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto,0.333795,0.639653,0.741686,0.741686,0.792306,0.697146,102,0.614205
7,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto,0.325923,0.642392,0.743966,0.743966,0.795844,0.698439,102,0.614062
8,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.307762,0.607087,0.717225,0.717225,0.763401,0.676317,102,0.587325
9,kmeans,raw,False,embedding__nvidia__llama_embed_nemotron_8b__texto,0.285314,0.602847,0.713901,0.713901,0.758952,0.673899,102,0.578991

========================================================================================================================
RAW EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_nivel_2 | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.417927,0.664034,0.742535,0.742535,0.743777,0.741298,102,0.641758
1,agglomerative,raw,False,embedding__openai__text_embedding_3_large__mea...,0.424154,0.653721,0.735107,0.735107,0.737159,0.733067,102,0.637022
2,agglomerative,raw,False,embedding__openai__text_embedding_3_large__tru...,0.422598,0.653074,0.734089,0.734089,0.735059,0.733121,102,0.635962
3,agglomerative,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.419625,0.653869,0.732944,0.732944,0.722943,0.743225,102,0.634845
4,agglomerative,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.381176,0.653866,0.735811,0.735811,0.734706,0.736919,102,0.626666
5,kmeans,raw,False,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.332401,0.646337,0.745664,0.745664,0.793924,0.702934,102,0.617516
6,kmeans,raw,False,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.328628,0.643094,0.744382,0.744382,0.795145,0.699712,102,0.615122
7,kmeans,raw,False,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.316783,0.645766,0.746878,0.746878,0.800565,0.699939,102,0.614076
8,kmeans,raw,False,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.313266,0.634552,0.737544,0.737544,0.785623,0.695010,102,0.605726
9,kmeans,raw,False,embedding__openai__text_embedding_3_large__mea...,0.310421,0.625785,0.731222,0.731222,0.779696,0.688422,102,0.599662

###########################
### RESULTADOS COM UMAP ###
###########################

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: MPV_612_2013 | NIVEL: tema | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__jinaai__jina_embeddings_v5_text_sma...,0.131366,0.367000,0.677350,0.677350,0.784543,0.595927,58,0.463266
1,agglomerative,umap,True,embedding__PORTULAN__serafim_900m_portuguese_p...,0.113057,0.374708,0.681735,0.681735,0.791363,0.598784,58,0.462809
2,agglomerative,umap,True,embedding__openai__text_embedding_3_large__tru...,0.109532,0.367375,0.678924,0.678924,0.791198,0.594555,58,0.458689
3,agglomerative,umap,True,embedding__openai__text_embedding_3_large__mea...,0.111626,0.359845,0.672074,0.672074,0.777965,0.591556,58,0.453905
4,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.105944,0.356959,0.672287,0.672287,0.781348,0.589942,58,0.451869
5,kmeans,umap,True,embedding__openai__text_embedding_3_large__tru...,0.105523,0.364031,0.683292,0.683292,0.809259,0.591258,58,0.459034
6,kmeans,umap,True,embedding__PORTULAN__serafim_900m_portuguese_p...,0.103369,0.357004,0.676882,0.676882,0.795882,0.588839,58,0.453534
7,kmeans,umap,True,embedding__openai__text_embedding_3_large__mea...,0.098222,0.356905,0.677243,0.677243,0.797497,0.588504,58,0.452404
8,kmeans,umap,True,embedding__google__gemini_embedding_2__meanpoo...,0.089167,0.327920,0.664436,0.664436,0.785168,0.575885,58,0.436490
9,kmeans,umap,True,embedding__PORTULAN__serafim_900m_portuguese_p...,0.085948,0.326707,0.664999,0.664999,0.787643,0.575403,58,0.435663

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: MPV_612_2013 | NIVEL: tema | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.117379,0.377677,0.686116,0.686116,0.803739,0.598526,58,0.466822
1,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.107406,0.369228,0.682451,0.682451,0.801373,0.594263,58,0.460384
2,agglomerative,umap,True,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.104365,0.365464,0.679711,0.679711,0.796406,0.592843,58,0.457313
3,agglomerative,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto,0.104378,0.362589,0.678852,0.678852,0.795134,0.592241,58,0.456168
4,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.093751,0.340517,0.669756,0.669756,0.789914,0.581327,58,0.443445
5,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.109398,0.370151,0.685664,0.685664,0.810762,0.594010,58,0.462719
6,kmeans,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.102948,0.360848,0.681408,0.681408,0.805914,0.590224,58,0.456653
7,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.105720,0.358137,0.680911,0.680911,0.807523,0.588621,58,0.456420
8,kmeans,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto,0.109271,0.352767,0.675085,0.675085,0.793526,0.587408,58,0.453052
9,kmeans,umap,True,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.093498,0.342032,0.669644,0.669644,0.787982,0.582208,58,0.443705

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: MPV_612_2013 | NIVEL: tema | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__openai__text_embedding_3_large__tru...,0.126928,0.378527,0.680638,0.680638,0.784545,0.601035,58,0.466683
1,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.112189,0.373027,0.682644,0.682644,0.797972,0.596442,58,0.462626
2,agglomerative,umap,True,embedding__openai__text_embedding_3_large__mea...,0.106236,0.366346,0.678420,0.678420,0.789765,0.594592,58,0.457356
3,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.109370,0.357565,0.676643,0.676643,0.794429,0.589275,58,0.455055
4,agglomerative,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.103290,0.355903,0.675001,0.675001,0.790867,0.588746,58,0.452299
5,kmeans,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.099797,0.360163,0.680232,0.680232,0.802832,0.590116,58,0.455106
6,kmeans,umap,True,embedding__PORTULAN__serafim_900m_portuguese_p...,0.103164,0.351143,0.675558,0.675558,0.796779,0.586352,58,0.451356
7,kmeans,umap,True,embedding__google__gemini_embedding_2__trunc81...,0.093514,0.350006,0.678123,0.678123,0.806545,0.584980,58,0.449942
8,kmeans,umap,True,embedding__openai__text_embedding_3_large__mea...,0.099948,0.349235,0.673551,0.673551,0.791956,0.585946,58,0.449071
9,kmeans,umap,True,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.091930,0.348887,0.675675,0.675675,0.799606,0.585005,58,0.448042

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PEC_6_2019 | NIVEL: tema | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.383638,0.551251,0.695384,0.695384,0.705206,0.685832,29,0.581414
1,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.389601,0.541618,0.687664,0.687664,0.696075,0.679454,29,0.576636
2,agglomerative,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.356587,0.503949,0.661716,0.661716,0.670129,0.653511,29,0.545992
3,agglomerative,umap,True,embedding__google__gemini_embedding_2__meanpoo...,0.330088,0.505390,0.667958,0.667958,0.683261,0.653325,29,0.542849
4,agglomerative,umap,True,embedding__google__gemini_embedding_2__trunc81...,0.325707,0.508043,0.665548,0.665548,0.671823,0.659389,29,0.541211
5,kmeans,umap,True,embedding__google__gemini_embedding_2__meanpoo...,0.386858,0.538250,0.693340,0.693340,0.716738,0.671420,29,0.577947
6,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.357990,0.524582,0.682031,0.682031,0.700614,0.664409,29,0.561659
7,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.353637,0.520009,0.677441,0.677441,0.692612,0.662921,29,0.557132
8,kmeans,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.362360,0.499177,0.668445,0.668445,0.692175,0.646289,29,0.549607
9,kmeans,umap,True,embedding__google__gemini_embedding_2__trunc81...,0.326125,0.491366,0.662635,0.662635,0.685619,0.641142,29,0.535690

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PEC_6_2019 | NIVEL: tema | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto,0.584656,0.713732,0.805503,0.805503,0.812952,0.798189,29,0.727349
1,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.574795,0.716108,0.806355,0.806355,0.812464,0.800338,29,0.725903
2,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.548221,0.721112,0.810666,0.810666,0.818850,0.802643,29,0.722666
3,agglomerative,umap,True,embedding__jinaai__jina_embeddings_v5_text_sma...,0.554217,0.677544,0.780274,0.780274,0.788800,0.771931,29,0.698077
4,agglomerative,umap,True,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.349095,0.534444,0.686548,0.686548,0.703174,0.670689,29,0.564159
5,kmeans,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto,0.539406,0.695029,0.798326,0.798326,0.828084,0.770632,29,0.707772
6,kmeans,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.549915,0.690422,0.794761,0.794761,0.823065,0.768339,29,0.707465
7,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.535827,0.695752,0.797784,0.797784,0.824498,0.772746,29,0.706786
8,kmeans,umap,True,embedding__jinaai__jina_embeddings_v5_text_sma...,0.481744,0.626305,0.752365,0.752365,0.779203,0.727314,29,0.653195
9,kmeans,umap,True,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.371573,0.555085,0.706211,0.706211,0.733865,0.680565,29,0.584770

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PEC_6_2019 | NIVEL: tema | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.554534,0.725291,0.815332,0.815332,0.831659,0.799634,29,0.727622
1,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.558719,0.705842,0.803369,0.803369,0.824460,0.783330,29,0.717825
2,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.547075,0.711307,0.805519,0.805519,0.821824,0.789848,29,0.717355
3,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.543538,0.704831,0.800655,0.800655,0.815524,0.786319,29,0.712420
4,agglomerative,umap,True,embedding__jinaai__jina_embeddings_v5_text_sma...,0.528494,0.668890,0.775099,0.775099,0.784904,0.765536,29,0.686896
5,kmeans,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.561909,0.707583,0.805096,0.805096,0.829873,0.781756,29,0.719921
6,kmeans,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.535578,0.700834,0.801077,0.801077,0.827408,0.776370,29,0.709642
7,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.528022,0.686920,0.791445,0.791445,0.815516,0.768755,29,0.699458
8,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.520724,0.685314,0.791427,0.791427,0.819218,0.765460,29,0.697223
9,kmeans,umap,True,embedding__openai__text_embedding_3_large__mea...,0.497487,0.653172,0.769677,0.769677,0.795384,0.745579,29,0.672503

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.351236,0.618116,0.815717,0.815717,0.846829,0.786811,261,0.650197
1,agglomerative,umap,True,embedding__google__gemini_embedding_2__meanpoo...,0.351828,0.618569,0.814290,0.814290,0.842326,0.788060,261,0.649744
2,agglomerative,umap,True,embedding__openai__text_embedding_3_large__tru...,0.349779,0.617929,0.812920,0.812920,0.839154,0.788277,261,0.648387
3,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.343069,0.613938,0.813060,0.813060,0.842829,0.785322,261,0.645782
4,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.339546,0.611572,0.812921,0.812921,0.844692,0.783453,261,0.644240
5,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.311190,0.597872,0.813051,0.813051,0.856130,0.774100,261,0.633791
6,kmeans,umap,True,embedding__google__gemini_embedding_2__meanpoo...,0.311969,0.591827,0.810111,0.810111,0.852936,0.771380,261,0.631004
7,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.304931,0.595715,0.811509,0.811509,0.853680,0.773308,261,0.630916
8,kmeans,umap,True,embedding__google__gemini_embedding_2__trunc81...,0.312037,0.592446,0.809288,0.809288,0.850180,0.772148,261,0.630765
9,kmeans,umap,True,embedding__openai__text_embedding_3_large__tru...,0.306309,0.594922,0.810613,0.810613,0.851844,0.773189,261,0.630614

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.374682,0.650701,0.832990,0.832990,0.867870,0.800806,261,0.672841
1,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.391429,0.646890,0.826297,0.826297,0.851036,0.802956,261,0.672728
2,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.364737,0.653680,0.835601,0.835601,0.872989,0.801284,261,0.672405
3,agglomerative,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto,0.366996,0.648050,0.832220,0.832220,0.868050,0.799231,261,0.669872
4,agglomerative,umap,True,embedding__nvidia__llama_embed_nemotron_8b__texto,0.364987,0.628646,0.818527,0.818527,0.845351,0.793353,261,0.657672
5,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.339228,0.644117,0.834633,0.834633,0.879064,0.794478,261,0.663153
6,kmeans,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto,0.335880,0.630405,0.827705,0.827705,0.870777,0.788693,261,0.655424
7,kmeans,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.334364,0.630018,0.828454,0.828454,0.873331,0.787965,261,0.655323
8,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.336935,0.616527,0.820224,0.820224,0.860922,0.783200,261,0.648478
9,kmeans,umap,True,embedding__nvidia__llama_embed_nemotron_8b__texto,0.321828,0.611566,0.819085,0.819085,0.861832,0.780378,261,0.642891

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.391136,0.667980,0.840282,0.840282,0.873262,0.809703,261,0.684920
1,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.384509,0.662809,0.838928,0.838928,0.874351,0.806263,261,0.681293
2,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.385257,0.655170,0.835542,0.835542,0.871306,0.802598,261,0.677878
3,agglomerative,umap,True,embedding__nvidia__llama_embed_nemotron_8b__te...,0.382531,0.654919,0.833125,0.833125,0.863997,0.804382,261,0.675925
4,agglomerative,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.362774,0.651117,0.833874,0.833874,0.870210,0.800450,261,0.670410
5,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.348322,0.647136,0.835852,0.835852,0.879850,0.796045,261,0.666790
6,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.332973,0.638217,0.833161,0.833161,0.880059,0.791008,261,0.659378
7,kmeans,umap,True,embedding__nvidia__llama_embed_nemotron_8b__te...,0.341697,0.631228,0.828718,0.828718,0.872952,0.788751,261,0.657591
8,kmeans,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.329163,0.631000,0.829506,0.829506,0.875512,0.788093,261,0.654794
9,kmeans,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.328524,0.630694,0.828579,0.828579,0.873080,0.788393,261,0.654094

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_macro | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__google__gemini_embedding_2__trunc81...,0.181098,0.459415,0.498889,0.498889,0.592425,0.430862,35,0.409573
1,agglomerative,umap,True,embedding__openai__text_embedding_3_large__tru...,0.156947,0.462349,0.501613,0.501613,0.598417,0.431768,35,0.405631
2,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.183708,0.453182,0.492471,0.492471,0.575863,0.430176,35,0.405458
3,agglomerative,umap,True,embedding__google__gemini_embedding_2__meanpoo...,0.158737,0.455895,0.495963,0.495963,0.592587,0.426432,35,0.401640
4,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.180596,0.439075,0.479158,0.479158,0.560755,0.418291,35,0.394497
5,kmeans,umap,True,embedding__openai__text_embedding_3_large__tru...,0.171204,0.478708,0.517046,0.517046,0.620562,0.443128,35,0.421001
6,kmeans,umap,True,embedding__google__gemini_embedding_2__meanpoo...,0.175561,0.460772,0.500595,0.500595,0.600982,0.428945,35,0.409381
7,kmeans,umap,True,embedding__google__gemini_embedding_2__trunc81...,0.157196,0.460727,0.500691,0.500691,0.605756,0.426684,35,0.404826
8,kmeans,umap,True,embedding__openai__text_embedding_3_large__mea...,0.149101,0.454783,0.494803,0.494803,0.591457,0.425301,35,0.398373
9,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.168671,0.444384,0.484950,0.484950,0.577745,0.417839,35,0.395739

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_macro | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__nvidia__llama_embed_nemotron_8b__texto,0.211788,0.483835,0.520663,0.520663,0.586924,0.467845,35,0.434237
1,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.182011,0.488244,0.525492,0.525492,0.622323,0.454736,35,0.430309
2,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.201831,0.479169,0.516402,0.516402,0.595923,0.455605,35,0.428451
3,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.177318,0.485327,0.522373,0.522373,0.612579,0.455324,35,0.426848
4,agglomerative,umap,True,embedding__openai__text_embedding_3_large__mea...,0.177949,0.464361,0.503064,0.503064,0.590259,0.438315,35,0.412110
5,kmeans,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.181613,0.500958,0.537483,0.537483,0.643288,0.461566,35,0.439384
6,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.183335,0.491797,0.529091,0.529091,0.633861,0.454043,35,0.433329
7,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.175358,0.477812,0.516164,0.516164,0.614830,0.444787,35,0.421375
8,kmeans,umap,True,embedding__nvidia__llama_embed_nemotron_8b__texto,0.159782,0.467266,0.505805,0.505805,0.592519,0.441232,35,0.409664
9,kmeans,umap,True,embedding__openai__text_embedding_3_large__mea...,0.162534,0.460574,0.500231,0.500231,0.599129,0.429358,35,0.405893

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_macro | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.215346,0.501785,0.537419,0.537419,0.626167,0.470704,35,0.447992
1,agglomerative,umap,True,embedding__nvidia__llama_embed_nemotron_8b__te...,0.206350,0.480277,0.516865,0.516865,0.580162,0.466021,35,0.430089
2,agglomerative,umap,True,embedding__openai__text_embedding_3_large__tru...,0.174415,0.478801,0.516671,0.516671,0.612596,0.446721,35,0.421640
3,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.180917,0.467520,0.505502,0.505502,0.589579,0.442412,35,0.414860
4,agglomerative,umap,True,embedding__openai__text_embedding_3_large__mea...,0.169625,0.470314,0.508681,0.508681,0.602560,0.440111,35,0.414325
5,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.207379,0.499493,0.535738,0.535738,0.635447,0.463076,35,0.444587
6,kmeans,umap,True,embedding__openai__text_embedding_3_large__mea...,0.180796,0.480877,0.519159,0.519159,0.621907,0.445548,35,0.424998
7,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.176887,0.474556,0.512597,0.512597,0.607492,0.443344,35,0.419159
8,kmeans,umap,True,embedding__openai__text_embedding_3_large__tru...,0.173508,0.472427,0.511189,0.511189,0.609837,0.440012,35,0.417078
9,kmeans,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.163896,0.467413,0.505764,0.505764,0.597631,0.438378,35,0.410710

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_nivel_2 | TIPO: Dispositivo (Sem Justificativa)
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__openai__text_embedding_3_large__mea...,0.359947,0.640137,0.735532,0.735532,0.768894,0.704945,102,0.617787
1,agglomerative,umap,True,embedding__google__gemini_embedding_2__meanpoo...,0.353997,0.638418,0.736382,0.736382,0.774539,0.701807,102,0.616295
2,agglomerative,umap,True,embedding__google__gemini_embedding_2__trunc81...,0.360923,0.635338,0.732443,0.732443,0.766295,0.701456,102,0.615287
3,agglomerative,umap,True,embedding__openai__text_embedding_3_large__tru...,0.356151,0.635602,0.733593,0.733593,0.769574,0.700826,102,0.614735
4,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.313046,0.614418,0.721044,0.721044,0.765353,0.681584,102,0.592388
5,kmeans,umap,True,embedding__google__gemini_embedding_2__meanpoo...,0.318711,0.627904,0.733727,0.733727,0.785503,0.688354,102,0.603517
6,kmeans,umap,True,embedding__openai__text_embedding_3_large__mea...,0.314812,0.624542,0.730962,0.730962,0.781843,0.686298,102,0.600319
7,kmeans,umap,True,embedding__openai__text_embedding_3_large__tru...,0.311070,0.619916,0.727333,0.727333,0.777036,0.683606,102,0.596413
8,kmeans,umap,True,embedding__google__gemini_embedding_2__trunc81...,0.308445,0.618908,0.726894,0.726894,0.777278,0.682645,102,0.595285
9,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.304186,0.608518,0.719029,0.719029,0.767923,0.675989,102,0.587691

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_nivel_2 | TIPO: Texto Bruto / Original
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.375781,0.672636,0.763073,0.763073,0.808299,0.722639,102,0.643641
1,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.351828,0.666943,0.759349,0.759349,0.805523,0.718181,102,0.634367
2,agglomerative,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto,0.359948,0.663615,0.755492,0.755492,0.797849,0.717405,102,0.633637
3,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.363503,0.649673,0.745571,0.745571,0.786673,0.708551,102,0.626080
4,agglomerative,umap,True,embedding__openai__text_embedding_3_large__tru...,0.376824,0.639489,0.736205,0.736205,0.770794,0.704587,102,0.622181
5,kmeans,umap,True,embedding__joaorobson__harrier_oss_v1_27b__texto,0.350493,0.663418,0.759023,0.759023,0.812118,0.712445,102,0.632989
6,kmeans,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto,0.334145,0.654486,0.752689,0.752689,0.805924,0.706052,102,0.623503
7,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto,0.324865,0.649035,0.749054,0.749054,0.802437,0.702330,102,0.618002
8,kmeans,umap,True,embedding__nvidia__llama_embed_nemotron_8b__texto,0.325658,0.633945,0.737991,0.737991,0.789689,0.692646,102,0.608896
9,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.316013,0.631618,0.736046,0.736046,0.787116,0.691199,102,0.604931

========================================================================================================================
UMAP EMBEDDINGS
MATERIA: PLP_68_2024 | NIVEL: tema_nivel_2 | TIPO: Texto Pré-processado Integral
========================================================================================================================

,algoritmo,embedding_space,use_umap,embedding,ari,ami,nmi,v_measure,homogeneity,completeness,n_clusters_pred,score_geral
0,agglomerative,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.365600,0.670509,0.760895,0.760895,0.802557,0.723345,102,0.639475
1,agglomerative,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.355694,0.668629,0.760342,0.760342,0.805933,0.719633,102,0.636252
2,agglomerative,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.352662,0.664621,0.758696,0.758696,0.808333,0.714803,102,0.633669
3,agglomerative,umap,True,embedding__openai__text_embedding_3_large__mea...,0.360545,0.662764,0.755190,0.755190,0.799022,0.715916,102,0.633422
4,agglomerative,umap,True,embedding__nvidia__llama_embed_nemotron_8b__te...,0.355367,0.659092,0.753010,0.753010,0.795649,0.714709,102,0.630120
5,kmeans,umap,True,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.363872,0.673421,0.766025,0.766025,0.819101,0.719409,102,0.642336
6,kmeans,umap,True,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.358665,0.674510,0.766418,0.766418,0.817948,0.720995,102,0.641503
7,kmeans,umap,True,embedding__openai__text_embedding_3_large__tru...,0.346626,0.656230,0.753650,0.753650,0.805681,0.707932,102,0.627539
8,kmeans,umap,True,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.338054,0.657121,0.754548,0.754548,0.807794,0.707887,102,0.626067
9,kmeans,umap,True,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.336681,0.651589,0.750938,0.750938,0.804802,0.703833,102,0.622537